<?php
/**
 * AssetsApiTest
 * PHP version 8.1
 *
 * @package  PayChainSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PayChainSdk\Test\Api;

use PayChainSdk\Configuration;
use PayChainSdk\ApiException;
use PayChainSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AssetsApiTest Class Doc Comment
 *
 * @package  PayChainSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AssetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateAsset
     *
     * Activate an asset.
     *
     */
    public function testActivateAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for burnAsset
     *
     * Burn loyalty value.
     *
     */
    public function testBurnAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAsset
     *
     * Create an asset.
     *
     */
    public function testCreateAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for earnAsset
     *
     * Evaluate earn rules and award points.
     *
     */
    public function testEarnAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAsset
     *
     * Get an asset.
     *
     */
    public function testGetAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for issueAsset
     *
     * Issue loyalty value.
     *
     */
    public function testIssueAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssets
     *
     * List assets.
     *
     */
    public function testListAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redeemAsset
     *
     * Redeem loyalty value.
     *
     */
    public function testRedeemAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferAsset
     *
     * Transfer loyalty value.
     *
     */
    public function testTransferAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
