/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PayChain.Sdk.Model;
using PayChain.Sdk.Client;
using System.Reflection;

namespace PayChain.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Balance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BalanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Balance
        //private Balance instance;

        public BalanceTests()
        {
            // TODO uncomment below to create an instance of Balance
            //instance = new Balance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Balance
        /// </summary>
        [Fact]
        public void BalanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Balance
            //Assert.IsType<Balance>(instance);
        }

        /// <summary>
        /// Test the property 'AssetCode'
        /// </summary>
        [Fact]
        public void AssetCodeTest()
        {
            // TODO unit test for the property 'AssetCode'
        }

        /// <summary>
        /// Test the property 'IssuerPublicKey'
        /// </summary>
        [Fact]
        public void IssuerPublicKeyTest()
        {
            // TODO unit test for the property 'IssuerPublicKey'
        }

        /// <summary>
        /// Test the property 'VarBalance'
        /// </summary>
        [Fact]
        public void VarBalanceTest()
        {
            // TODO unit test for the property 'VarBalance'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
