/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PayChain.Sdk.Model;
using PayChain.Sdk.Client;
using System.Reflection;

namespace PayChain.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAssetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAssetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAssetRequest
        //private CreateAssetRequest instance;

        public CreateAssetRequestTests()
        {
            // TODO uncomment below to create an instance of CreateAssetRequest
            //instance = new CreateAssetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAssetRequest
        /// </summary>
        [Fact]
        public void CreateAssetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAssetRequest
            //Assert.IsType<CreateAssetRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AssetCode'
        /// </summary>
        [Fact]
        public void AssetCodeTest()
        {
            // TODO unit test for the property 'AssetCode'
        }

        /// <summary>
        /// Test the property 'AssetName'
        /// </summary>
        [Fact]
        public void AssetNameTest()
        {
            // TODO unit test for the property 'AssetName'
        }

        /// <summary>
        /// Test the property 'AssetType'
        /// </summary>
        [Fact]
        public void AssetTypeTest()
        {
            // TODO unit test for the property 'AssetType'
        }

        /// <summary>
        /// Test the property 'ExpiryPolicy'
        /// </summary>
        [Fact]
        public void ExpiryPolicyTest()
        {
            // TODO unit test for the property 'ExpiryPolicy'
        }

        /// <summary>
        /// Test the property 'ExpiryDays'
        /// </summary>
        [Fact]
        public void ExpiryDaysTest()
        {
            // TODO unit test for the property 'ExpiryDays'
        }
    }
}
