/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PayChain.Sdk.Model;
using PayChain.Sdk.Client;
using System.Reflection;

namespace PayChain.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorResponseMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorResponseMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorResponseMessage
        //private ErrorResponseMessage instance;

        public ErrorResponseMessageTests()
        {
            // TODO uncomment below to create an instance of ErrorResponseMessage
            //instance = new ErrorResponseMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorResponseMessage
        /// </summary>
        [Fact]
        public void ErrorResponseMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorResponseMessage
            //Assert.IsType<ErrorResponseMessage>(instance);
        }
    }
}
