/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PayChain.Sdk.Model;
using PayChain.Sdk.Client;
using System.Reflection;

namespace PayChain.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MintRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MintRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MintRequest
        //private MintRequest instance;

        public MintRequestTests()
        {
            // TODO uncomment below to create an instance of MintRequest
            //instance = new MintRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MintRequest
        /// </summary>
        [Fact]
        public void MintRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MintRequest
            //Assert.IsType<MintRequest>(instance);
        }

        /// <summary>
        /// Test the property 'DestinationWalletId'
        /// </summary>
        [Fact]
        public void DestinationWalletIdTest()
        {
            // TODO unit test for the property 'DestinationWalletId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'FundingReference'
        /// </summary>
        [Fact]
        public void FundingReferenceTest()
        {
            // TODO unit test for the property 'FundingReference'
        }
    }
}
