/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PayChain.Sdk.Model;
using PayChain.Sdk.Client;
using System.Reflection;

namespace PayChain.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SuspendStablecoinRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuspendStablecoinRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuspendStablecoinRequest
        //private SuspendStablecoinRequest instance;

        public SuspendStablecoinRequestTests()
        {
            // TODO uncomment below to create an instance of SuspendStablecoinRequest
            //instance = new SuspendStablecoinRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuspendStablecoinRequest
        /// </summary>
        [Fact]
        public void SuspendStablecoinRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuspendStablecoinRequest
            //Assert.IsType<SuspendStablecoinRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
    }
}
