/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PayChain.Sdk.Model;
using PayChain.Sdk.Client;
using System.Reflection;

namespace PayChain.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Wallet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Wallet
        //private Wallet instance;

        public WalletTests()
        {
            // TODO uncomment below to create an instance of Wallet
            //instance = new Wallet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Wallet
        /// </summary>
        [Fact]
        public void WalletInstanceTest()
        {
            // TODO uncomment below to test "IsType" Wallet
            //Assert.IsType<Wallet>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'OwnerType'
        /// </summary>
        [Fact]
        public void OwnerTypeTest()
        {
            // TODO unit test for the property 'OwnerType'
        }

        /// <summary>
        /// Test the property 'OwnerReference'
        /// </summary>
        [Fact]
        public void OwnerReferenceTest()
        {
            // TODO unit test for the property 'OwnerReference'
        }

        /// <summary>
        /// Test the property 'StellarAccountId'
        /// </summary>
        [Fact]
        public void StellarAccountIdTest()
        {
            // TODO unit test for the property 'StellarAccountId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
