/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PayChain.Sdk.Model;
using PayChain.Sdk.Client;
using System.Reflection;

namespace PayChain.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookEndpointWithSecret
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookEndpointWithSecretTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookEndpointWithSecret
        //private WebhookEndpointWithSecret instance;

        public WebhookEndpointWithSecretTests()
        {
            // TODO uncomment below to create an instance of WebhookEndpointWithSecret
            //instance = new WebhookEndpointWithSecret();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookEndpointWithSecret
        /// </summary>
        [Fact]
        public void WebhookEndpointWithSecretInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookEndpointWithSecret
            //Assert.IsType<WebhookEndpointWithSecret>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
    }
}
