<?php
/**
 * CreateAssetRequest
 *
 * PHP version 8.1
 *
 * @package  PayChainSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayChainSdk\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use PayChainSdk\ObjectSerializer;

/**
 * CreateAssetRequest Class Doc Comment
 *
 * @package  PayChainSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateAssetRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'CreateAssetRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'assetCode' => 'string',
        'assetName' => 'string',
        'assetType' => 'string',
        'expiryPolicy' => 'string',
        'expiryDays' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'assetCode' => null,
        'assetName' => null,
        'assetType' => null,
        'expiryPolicy' => null,
        'expiryDays' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'assetCode' => false,
        'assetName' => false,
        'assetType' => false,
        'expiryPolicy' => false,
        'expiryDays' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'assetCode' => 'assetCode',
        'assetName' => 'assetName',
        'assetType' => 'assetType',
        'expiryPolicy' => 'expiryPolicy',
        'expiryDays' => 'expiryDays'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'assetCode' => 'setAssetCode',
        'assetName' => 'setAssetName',
        'assetType' => 'setAssetType',
        'expiryPolicy' => 'setExpiryPolicy',
        'expiryDays' => 'setExpiryDays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'assetCode' => 'getAssetCode',
        'assetName' => 'getAssetName',
        'assetType' => 'getAssetType',
        'expiryPolicy' => 'getExpiryPolicy',
        'expiryDays' => 'getExpiryDays'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const ASSET_TYPE_LOYALTY_POINT = 'LOYALTY_POINT';
    public const EXPIRY_POLICY_NONE = 'NONE';
    public const EXPIRY_POLICY_FIXED = 'FIXED';
    public const EXPIRY_POLICY_ROLLING = 'ROLLING';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAssetTypeAllowableValues()
    {
        return [
            self::ASSET_TYPE_LOYALTY_POINT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getExpiryPolicyAllowableValues()
    {
        return [
            self::EXPIRY_POLICY_NONE,
            self::EXPIRY_POLICY_FIXED,
            self::EXPIRY_POLICY_ROLLING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('assetCode', $data ?? [], null);
        $this->setIfExists('assetName', $data ?? [], null);
        $this->setIfExists('assetType', $data ?? [], 'LOYALTY_POINT');
        $this->setIfExists('expiryPolicy', $data ?? [], 'NONE');
        $this->setIfExists('expiryDays', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['assetCode'] === null) {
            $invalidProperties[] = "'assetCode' can't be null";
        }
        if (!preg_match("/^[A-Za-z0-9]{1,12}$/", $this->container['assetCode'])) {
            $invalidProperties[] = "invalid value for 'assetCode', must be conform to the pattern /^[A-Za-z0-9]{1,12}$/.";
        }

        if ($this->container['assetName'] === null) {
            $invalidProperties[] = "'assetName' can't be null";
        }
        if ((mb_strlen($this->container['assetName']) > 200)) {
            $invalidProperties[] = "invalid value for 'assetName', the character length must be smaller than or equal to 200.";
        }

        if ((mb_strlen($this->container['assetName']) < 1)) {
            $invalidProperties[] = "invalid value for 'assetName', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = self::getAssetTypeAllowableValues();
        if (!is_null($this->container['assetType']) && !in_array($this->container['assetType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'assetType', must be one of '%s'",
                $this->container['assetType'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = self::getExpiryPolicyAllowableValues();
        if (!is_null($this->container['expiryPolicy']) && !in_array($this->container['expiryPolicy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'expiryPolicy', must be one of '%s'",
                $this->container['expiryPolicy'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['expiryDays']) && ($this->container['expiryDays'] < 1)) {
            $invalidProperties[] = "invalid value for 'expiryDays', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets assetCode
     *
     * @return string
     */
    public function getAssetCode(): string
    {
        return $this->container['assetCode'];
    }

    /**
     * Sets assetCode
     *
     * @param string $assetCode assetCode
     *
     * @return $this
     */
    public function setAssetCode(string $assetCode): static
    {
        if (is_null($assetCode)) {
            throw new InvalidArgumentException('non-nullable assetCode cannot be null');
        }

        if ((!preg_match("/^[A-Za-z0-9]{1,12}$/", ObjectSerializer::toString($assetCode)))) {
            throw new InvalidArgumentException("invalid value for \$assetCode when calling CreateAssetRequest., must conform to the pattern /^[A-Za-z0-9]{1,12}$/.");
        }

        $this->container['assetCode'] = $assetCode;

        return $this;
    }

    /**
     * Gets assetName
     *
     * @return string
     */
    public function getAssetName(): string
    {
        return $this->container['assetName'];
    }

    /**
     * Sets assetName
     *
     * @param string $assetName assetName
     *
     * @return $this
     */
    public function setAssetName(string $assetName): static
    {
        if (is_null($assetName)) {
            throw new InvalidArgumentException('non-nullable assetName cannot be null');
        }
        if ((mb_strlen($assetName) > 200)) {
            throw new InvalidArgumentException('invalid length for $assetName when calling CreateAssetRequest., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($assetName) < 1)) {
            throw new InvalidArgumentException('invalid length for $assetName when calling CreateAssetRequest., must be bigger than or equal to 1.');
        }

        $this->container['assetName'] = $assetName;

        return $this;
    }

    /**
     * Gets assetType
     *
     * @return string|null
     */
    public function getAssetType(): ?string
    {
        return $this->container['assetType'];
    }

    /**
     * Sets assetType
     *
     * @param string|null $assetType assetType
     *
     * @return $this
     */
    public function setAssetType(?string $assetType): static
    {
        if (is_null($assetType)) {
            throw new InvalidArgumentException('non-nullable assetType cannot be null');
        }
        $allowedValues = self::getAssetTypeAllowableValues();
        if (!in_array($assetType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'assetType', must be one of '%s'",
                    $assetType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['assetType'] = $assetType;

        return $this;
    }

    /**
     * Gets expiryPolicy
     *
     * @return string|null
     */
    public function getExpiryPolicy(): ?string
    {
        return $this->container['expiryPolicy'];
    }

    /**
     * Sets expiryPolicy
     *
     * @param string|null $expiryPolicy expiryPolicy
     *
     * @return $this
     */
    public function setExpiryPolicy(?string $expiryPolicy): static
    {
        if (is_null($expiryPolicy)) {
            throw new InvalidArgumentException('non-nullable expiryPolicy cannot be null');
        }
        $allowedValues = self::getExpiryPolicyAllowableValues();
        if (!in_array($expiryPolicy, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'expiryPolicy', must be one of '%s'",
                    $expiryPolicy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['expiryPolicy'] = $expiryPolicy;

        return $this;
    }

    /**
     * Gets expiryDays
     *
     * @return int|null
     */
    public function getExpiryDays(): ?int
    {
        return $this->container['expiryDays'];
    }

    /**
     * Sets expiryDays
     *
     * @param int|null $expiryDays expiryDays
     *
     * @return $this
     */
    public function setExpiryDays(?int $expiryDays): static
    {
        if (is_null($expiryDays)) {
            throw new InvalidArgumentException('non-nullable expiryDays cannot be null');
        }

        if (($expiryDays < 1)) {
            throw new InvalidArgumentException('invalid value for $expiryDays when calling CreateAssetRequest., must be bigger than or equal to 1.');
        }

        $this->container['expiryDays'] = $expiryDays;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


