<?php
/**
 * CreateWalletRequest
 *
 * PHP version 8.1
 *
 * @package  PayChainSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayChainSdk\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use PayChainSdk\ObjectSerializer;

/**
 * CreateWalletRequest Class Doc Comment
 *
 * @package  PayChainSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateWalletRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'CreateWalletRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'ownerType' => 'string',
        'ownerReference' => 'string',
        'externalReference' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'ownerType' => null,
        'ownerReference' => null,
        'externalReference' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'ownerType' => false,
        'ownerReference' => false,
        'externalReference' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'ownerType' => 'ownerType',
        'ownerReference' => 'ownerReference',
        'externalReference' => 'externalReference'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'ownerType' => 'setOwnerType',
        'ownerReference' => 'setOwnerReference',
        'externalReference' => 'setExternalReference'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'ownerType' => 'getOwnerType',
        'ownerReference' => 'getOwnerReference',
        'externalReference' => 'getExternalReference'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const OWNER_TYPE_CUSTOMER = 'CUSTOMER';
    public const OWNER_TYPE_MERCHANT = 'MERCHANT';
    public const OWNER_TYPE_ORGANIZATION = 'ORGANIZATION';
    public const OWNER_TYPE_TREASURY = 'TREASURY';
    public const OWNER_TYPE_CAMPAIGN = 'CAMPAIGN';
    public const OWNER_TYPE_SYSTEM = 'SYSTEM';
    public const OWNER_TYPE_REDEMPTION = 'REDEMPTION';
    public const OWNER_TYPE_SETTLEMENT = 'SETTLEMENT';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getOwnerTypeAllowableValues()
    {
        return [
            self::OWNER_TYPE_CUSTOMER,
            self::OWNER_TYPE_MERCHANT,
            self::OWNER_TYPE_ORGANIZATION,
            self::OWNER_TYPE_TREASURY,
            self::OWNER_TYPE_CAMPAIGN,
            self::OWNER_TYPE_SYSTEM,
            self::OWNER_TYPE_REDEMPTION,
            self::OWNER_TYPE_SETTLEMENT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ownerType', $data ?? [], null);
        $this->setIfExists('ownerReference', $data ?? [], null);
        $this->setIfExists('externalReference', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['ownerType'] === null) {
            $invalidProperties[] = "'ownerType' can't be null";
        }
        $allowedValues = self::getOwnerTypeAllowableValues();
        if (!is_null($this->container['ownerType']) && !in_array($this->container['ownerType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'ownerType', must be one of '%s'",
                $this->container['ownerType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['ownerReference'] === null) {
            $invalidProperties[] = "'ownerReference' can't be null";
        }
        if ((mb_strlen($this->container['ownerReference']) > 200)) {
            $invalidProperties[] = "invalid value for 'ownerReference', the character length must be smaller than or equal to 200.";
        }

        if ((mb_strlen($this->container['ownerReference']) < 1)) {
            $invalidProperties[] = "invalid value for 'ownerReference', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ownerType
     *
     * @return string
     */
    public function getOwnerType(): string
    {
        return $this->container['ownerType'];
    }

    /**
     * Sets ownerType
     *
     * @param string $ownerType ownerType
     *
     * @return $this
     */
    public function setOwnerType(string $ownerType): static
    {
        if (is_null($ownerType)) {
            throw new InvalidArgumentException('non-nullable ownerType cannot be null');
        }
        $allowedValues = self::getOwnerTypeAllowableValues();
        if (!in_array($ownerType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'ownerType', must be one of '%s'",
                    $ownerType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ownerType'] = $ownerType;

        return $this;
    }

    /**
     * Gets ownerReference
     *
     * @return string
     */
    public function getOwnerReference(): string
    {
        return $this->container['ownerReference'];
    }

    /**
     * Sets ownerReference
     *
     * @param string $ownerReference ownerReference
     *
     * @return $this
     */
    public function setOwnerReference(string $ownerReference): static
    {
        if (is_null($ownerReference)) {
            throw new InvalidArgumentException('non-nullable ownerReference cannot be null');
        }
        if ((mb_strlen($ownerReference) > 200)) {
            throw new InvalidArgumentException('invalid length for $ownerReference when calling CreateWalletRequest., must be smaller than or equal to 200.');
        }
        if ((mb_strlen($ownerReference) < 1)) {
            throw new InvalidArgumentException('invalid length for $ownerReference when calling CreateWalletRequest., must be bigger than or equal to 1.');
        }

        $this->container['ownerReference'] = $ownerReference;

        return $this;
    }

    /**
     * Gets externalReference
     *
     * @return string|null
     */
    public function getExternalReference(): ?string
    {
        return $this->container['externalReference'];
    }

    /**
     * Sets externalReference
     *
     * @param string|null $externalReference externalReference
     *
     * @return $this
     */
    public function setExternalReference(?string $externalReference): static
    {
        if (is_null($externalReference)) {
            throw new InvalidArgumentException('non-nullable externalReference cannot be null');
        }
        $this->container['externalReference'] = $externalReference;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


