<?php
/**
 * TokenRequest
 *
 * PHP version 8.1
 *
 * @package  PayChainSdk
 * @author   PayChain
 * @link     https://developer.paychain.cambobia.com
 */

/**
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated for PayChain
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is generated for PayChain. Do not edit this file manually.
 * https://developer.paychain.cambobia.com
 * Do not edit the class manually.
 */

namespace PayChainSdk\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use PayChainSdk\ObjectSerializer;

/**
 * TokenRequest Class Doc Comment
 *
 * @package  PayChainSdk
 * @author   PayChain
 * @link     https://developer.paychain.cambobia.com
 * @implements ArrayAccess<string, mixed>
 */
class TokenRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'TokenRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'grantType' => 'string',
        'clientId' => 'string',
        'clientSecret' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'grantType' => null,
        'clientId' => null,
        'clientSecret' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'grantType' => false,
        'clientId' => false,
        'clientSecret' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'grantType' => 'grant_type',
        'clientId' => 'client_id',
        'clientSecret' => 'client_secret'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'grantType' => 'setGrantType',
        'clientId' => 'setClientId',
        'clientSecret' => 'setClientSecret'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'grantType' => 'getGrantType',
        'clientId' => 'getClientId',
        'clientSecret' => 'getClientSecret'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const GRANT_TYPE_CLIENT_CREDENTIALS = 'client_credentials';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getGrantTypeAllowableValues()
    {
        return [
            self::GRANT_TYPE_CLIENT_CREDENTIALS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('grantType', $data ?? [], null);
        $this->setIfExists('clientId', $data ?? [], null);
        $this->setIfExists('clientSecret', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['grantType'] === null) {
            $invalidProperties[] = "'grantType' can't be null";
        }
        $allowedValues = self::getGrantTypeAllowableValues();
        if (!is_null($this->container['grantType']) && !in_array($this->container['grantType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'grantType', must be one of '%s'",
                $this->container['grantType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['clientId'] === null) {
            $invalidProperties[] = "'clientId' can't be null";
        }
        if ((mb_strlen($this->container['clientId']) < 1)) {
            $invalidProperties[] = "invalid value for 'clientId', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['clientSecret'] === null) {
            $invalidProperties[] = "'clientSecret' can't be null";
        }
        if ((mb_strlen($this->container['clientSecret']) < 1)) {
            $invalidProperties[] = "invalid value for 'clientSecret', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets grantType
     *
     * @return string
     */
    public function getGrantType(): string
    {
        return $this->container['grantType'];
    }

    /**
     * Sets grantType
     *
     * @param string $grantType grantType
     *
     * @return $this
     */
    public function setGrantType(string $grantType): static
    {
        if (is_null($grantType)) {
            throw new InvalidArgumentException('non-nullable grantType cannot be null');
        }
        $allowedValues = self::getGrantTypeAllowableValues();
        if (!in_array($grantType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'grantType', must be one of '%s'",
                    $grantType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['grantType'] = $grantType;

        return $this;
    }

    /**
     * Gets clientId
     *
     * @return string
     */
    public function getClientId(): string
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string $clientId clientId
     *
     * @return $this
     */
    public function setClientId(string $clientId): static
    {
        if (is_null($clientId)) {
            throw new InvalidArgumentException('non-nullable clientId cannot be null');
        }

        if ((mb_strlen($clientId) < 1)) {
            throw new InvalidArgumentException('invalid length for $clientId when calling TokenRequest., must be bigger than or equal to 1.');
        }

        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets clientSecret
     *
     * @return string
     */
    public function getClientSecret(): string
    {
        return $this->container['clientSecret'];
    }

    /**
     * Sets clientSecret
     *
     * @param string $clientSecret clientSecret
     *
     * @return $this
     */
    public function setClientSecret(string $clientSecret): static
    {
        if (is_null($clientSecret)) {
            throw new InvalidArgumentException('non-nullable clientSecret cannot be null');
        }

        if ((mb_strlen($clientSecret) < 1)) {
            throw new InvalidArgumentException('invalid length for $clientSecret when calling TokenRequest., must be bigger than or equal to 1.');
        }

        $this->container['clientSecret'] = $clientSecret;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


