/**
 *
 * Please note:
 * This class is generated for PayChain. Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.paychain.sdk.models.Asset
import com.paychain.sdk.models.BurnRequest
import com.paychain.sdk.models.CreateAssetRequest
import com.paychain.sdk.models.EarnRequest
import com.paychain.sdk.models.ErrorResponse
import com.paychain.sdk.models.IssueRequest
import com.paychain.sdk.models.RedeemRequest
import com.paychain.sdk.models.TransactionRecord
import com.paychain.sdk.models.TransferRequest

import com.squareup.moshi.Json

import com.paychain.sdk.infrastructure.ApiClient
import com.paychain.sdk.infrastructure.ApiResponse
import com.paychain.sdk.infrastructure.ClientException
import com.paychain.sdk.infrastructure.ClientError
import com.paychain.sdk.infrastructure.ServerException
import com.paychain.sdk.infrastructure.ServerError
import com.paychain.sdk.infrastructure.MultiValueMap
import com.paychain.sdk.infrastructure.PartConfig
import com.paychain.sdk.infrastructure.RequestConfig
import com.paychain.sdk.infrastructure.RequestMethod
import com.paychain.sdk.infrastructure.ResponseType
import com.paychain.sdk.infrastructure.Success
import com.paychain.sdk.infrastructure.toMultiValue

open class AssetsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.paychain.cambobia.com")
        }
    }

    /**
     * POST /api/v1/assets/{assetId}/activate
     * Activate an asset
     * 
     * @param assetId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Asset
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun activateAsset(assetId: kotlin.String, xCorrelationId: java.util.UUID? = null) : Asset {
        val localVarResponse = activateAssetWithHttpInfo(assetId = assetId, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Asset
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/assets/{assetId}/activate
     * Activate an asset
     * 
     * @param assetId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Asset?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun activateAssetWithHttpInfo(assetId: kotlin.String, xCorrelationId: java.util.UUID?) : ApiResponse<Asset?> {
        val localVariableConfig = activateAssetRequestConfig(assetId = assetId, xCorrelationId = xCorrelationId)

        return request<Unit, Asset>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation activateAsset
     *
     * @param assetId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun activateAssetRequestConfig(assetId: kotlin.String, xCorrelationId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/assets/{assetId}/activate".replace("{"+"assetId"+"}", encodeURIComponent(assetId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/assets/{assetId}/burn
     * Burn loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param burnRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return TransactionRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun burnAsset(assetId: kotlin.String, idempotencyKey: kotlin.String, burnRequest: BurnRequest, xCorrelationId: java.util.UUID? = null) : TransactionRecord {
        val localVarResponse = burnAssetWithHttpInfo(assetId = assetId, idempotencyKey = idempotencyKey, burnRequest = burnRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TransactionRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/assets/{assetId}/burn
     * Burn loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param burnRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<TransactionRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun burnAssetWithHttpInfo(assetId: kotlin.String, idempotencyKey: kotlin.String, burnRequest: BurnRequest, xCorrelationId: java.util.UUID?) : ApiResponse<TransactionRecord?> {
        val localVariableConfig = burnAssetRequestConfig(assetId = assetId, idempotencyKey = idempotencyKey, burnRequest = burnRequest, xCorrelationId = xCorrelationId)

        return request<BurnRequest, TransactionRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation burnAsset
     *
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param burnRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun burnAssetRequestConfig(assetId: kotlin.String, idempotencyKey: kotlin.String, burnRequest: BurnRequest, xCorrelationId: java.util.UUID?) : RequestConfig<BurnRequest> {
        val localVariableBody = burnRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/assets/{assetId}/burn".replace("{"+"assetId"+"}", encodeURIComponent(assetId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/assets
     * Create an asset
     * 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param createAssetRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Asset
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createAsset(idempotencyKey: kotlin.String, createAssetRequest: CreateAssetRequest, xCorrelationId: java.util.UUID? = null) : Asset {
        val localVarResponse = createAssetWithHttpInfo(idempotencyKey = idempotencyKey, createAssetRequest = createAssetRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Asset
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/assets
     * Create an asset
     * 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param createAssetRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Asset?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createAssetWithHttpInfo(idempotencyKey: kotlin.String, createAssetRequest: CreateAssetRequest, xCorrelationId: java.util.UUID?) : ApiResponse<Asset?> {
        val localVariableConfig = createAssetRequestConfig(idempotencyKey = idempotencyKey, createAssetRequest = createAssetRequest, xCorrelationId = xCorrelationId)

        return request<CreateAssetRequest, Asset>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createAsset
     *
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param createAssetRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun createAssetRequestConfig(idempotencyKey: kotlin.String, createAssetRequest: CreateAssetRequest, xCorrelationId: java.util.UUID?) : RequestConfig<CreateAssetRequest> {
        val localVariableBody = createAssetRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/assets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/assets/{assetId}/earn
     * Evaluate earn rules and award points
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param earnRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return TransactionRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun earnAsset(assetId: kotlin.String, idempotencyKey: kotlin.String, earnRequest: EarnRequest, xCorrelationId: java.util.UUID? = null) : TransactionRecord {
        val localVarResponse = earnAssetWithHttpInfo(assetId = assetId, idempotencyKey = idempotencyKey, earnRequest = earnRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TransactionRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/assets/{assetId}/earn
     * Evaluate earn rules and award points
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param earnRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<TransactionRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun earnAssetWithHttpInfo(assetId: kotlin.String, idempotencyKey: kotlin.String, earnRequest: EarnRequest, xCorrelationId: java.util.UUID?) : ApiResponse<TransactionRecord?> {
        val localVariableConfig = earnAssetRequestConfig(assetId = assetId, idempotencyKey = idempotencyKey, earnRequest = earnRequest, xCorrelationId = xCorrelationId)

        return request<EarnRequest, TransactionRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation earnAsset
     *
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param earnRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun earnAssetRequestConfig(assetId: kotlin.String, idempotencyKey: kotlin.String, earnRequest: EarnRequest, xCorrelationId: java.util.UUID?) : RequestConfig<EarnRequest> {
        val localVariableBody = earnRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/assets/{assetId}/earn".replace("{"+"assetId"+"}", encodeURIComponent(assetId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/assets/{assetId}
     * Get an asset
     * 
     * @param assetId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Asset
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAsset(assetId: kotlin.String, xCorrelationId: java.util.UUID? = null) : Asset {
        val localVarResponse = getAssetWithHttpInfo(assetId = assetId, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Asset
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/assets/{assetId}
     * Get an asset
     * 
     * @param assetId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Asset?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getAssetWithHttpInfo(assetId: kotlin.String, xCorrelationId: java.util.UUID?) : ApiResponse<Asset?> {
        val localVariableConfig = getAssetRequestConfig(assetId = assetId, xCorrelationId = xCorrelationId)

        return request<Unit, Asset>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAsset
     *
     * @param assetId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun getAssetRequestConfig(assetId: kotlin.String, xCorrelationId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/assets/{assetId}".replace("{"+"assetId"+"}", encodeURIComponent(assetId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/assets/{assetId}/issue
     * Issue loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param issueRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return TransactionRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun issueAsset(assetId: kotlin.String, idempotencyKey: kotlin.String, issueRequest: IssueRequest, xCorrelationId: java.util.UUID? = null) : TransactionRecord {
        val localVarResponse = issueAssetWithHttpInfo(assetId = assetId, idempotencyKey = idempotencyKey, issueRequest = issueRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TransactionRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/assets/{assetId}/issue
     * Issue loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param issueRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<TransactionRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun issueAssetWithHttpInfo(assetId: kotlin.String, idempotencyKey: kotlin.String, issueRequest: IssueRequest, xCorrelationId: java.util.UUID?) : ApiResponse<TransactionRecord?> {
        val localVariableConfig = issueAssetRequestConfig(assetId = assetId, idempotencyKey = idempotencyKey, issueRequest = issueRequest, xCorrelationId = xCorrelationId)

        return request<IssueRequest, TransactionRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation issueAsset
     *
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param issueRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun issueAssetRequestConfig(assetId: kotlin.String, idempotencyKey: kotlin.String, issueRequest: IssueRequest, xCorrelationId: java.util.UUID?) : RequestConfig<IssueRequest> {
        val localVariableBody = issueRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/assets/{assetId}/issue".replace("{"+"assetId"+"}", encodeURIComponent(assetId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/assets
     * List assets
     * 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return kotlin.collections.List<Asset>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAssets(xCorrelationId: java.util.UUID? = null) : kotlin.collections.List<Asset> {
        val localVarResponse = listAssetsWithHttpInfo(xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Asset>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/assets
     * List assets
     * 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<kotlin.collections.List<Asset>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listAssetsWithHttpInfo(xCorrelationId: java.util.UUID?) : ApiResponse<kotlin.collections.List<Asset>?> {
        val localVariableConfig = listAssetsRequestConfig(xCorrelationId = xCorrelationId)

        return request<Unit, kotlin.collections.List<Asset>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAssets
     *
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun listAssetsRequestConfig(xCorrelationId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/assets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/assets/{assetId}/redeem
     * Redeem loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param redeemRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return TransactionRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun redeemAsset(assetId: kotlin.String, idempotencyKey: kotlin.String, redeemRequest: RedeemRequest, xCorrelationId: java.util.UUID? = null) : TransactionRecord {
        val localVarResponse = redeemAssetWithHttpInfo(assetId = assetId, idempotencyKey = idempotencyKey, redeemRequest = redeemRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TransactionRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/assets/{assetId}/redeem
     * Redeem loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param redeemRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<TransactionRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun redeemAssetWithHttpInfo(assetId: kotlin.String, idempotencyKey: kotlin.String, redeemRequest: RedeemRequest, xCorrelationId: java.util.UUID?) : ApiResponse<TransactionRecord?> {
        val localVariableConfig = redeemAssetRequestConfig(assetId = assetId, idempotencyKey = idempotencyKey, redeemRequest = redeemRequest, xCorrelationId = xCorrelationId)

        return request<RedeemRequest, TransactionRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation redeemAsset
     *
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param redeemRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun redeemAssetRequestConfig(assetId: kotlin.String, idempotencyKey: kotlin.String, redeemRequest: RedeemRequest, xCorrelationId: java.util.UUID?) : RequestConfig<RedeemRequest> {
        val localVariableBody = redeemRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/assets/{assetId}/redeem".replace("{"+"assetId"+"}", encodeURIComponent(assetId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/assets/{assetId}/transfer
     * Transfer loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param transferRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return TransactionRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun transferAsset(assetId: kotlin.String, idempotencyKey: kotlin.String, transferRequest: TransferRequest, xCorrelationId: java.util.UUID? = null) : TransactionRecord {
        val localVarResponse = transferAssetWithHttpInfo(assetId = assetId, idempotencyKey = idempotencyKey, transferRequest = transferRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TransactionRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/assets/{assetId}/transfer
     * Transfer loyalty value
     * 
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param transferRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<TransactionRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun transferAssetWithHttpInfo(assetId: kotlin.String, idempotencyKey: kotlin.String, transferRequest: TransferRequest, xCorrelationId: java.util.UUID?) : ApiResponse<TransactionRecord?> {
        val localVariableConfig = transferAssetRequestConfig(assetId = assetId, idempotencyKey = idempotencyKey, transferRequest = transferRequest, xCorrelationId = xCorrelationId)

        return request<TransferRequest, TransactionRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation transferAsset
     *
     * @param assetId 
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param transferRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun transferAssetRequestConfig(assetId: kotlin.String, idempotencyKey: kotlin.String, transferRequest: TransferRequest, xCorrelationId: java.util.UUID?) : RequestConfig<TransferRequest> {
        val localVariableBody = transferRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/assets/{assetId}/transfer".replace("{"+"assetId"+"}", encodeURIComponent(assetId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
