/**
 *
 * Please note:
 * This class is generated for PayChain. Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.paychain.sdk.models.ApproveStablecoinGateRequest
import com.paychain.sdk.models.CreateStablecoinRequest
import com.paychain.sdk.models.Stablecoin
import com.paychain.sdk.models.SuspendStablecoinRequest

import com.squareup.moshi.Json

import com.paychain.sdk.infrastructure.ApiClient
import com.paychain.sdk.infrastructure.ApiResponse
import com.paychain.sdk.infrastructure.ClientException
import com.paychain.sdk.infrastructure.ClientError
import com.paychain.sdk.infrastructure.ServerException
import com.paychain.sdk.infrastructure.ServerError
import com.paychain.sdk.infrastructure.MultiValueMap
import com.paychain.sdk.infrastructure.PartConfig
import com.paychain.sdk.infrastructure.RequestConfig
import com.paychain.sdk.infrastructure.RequestMethod
import com.paychain.sdk.infrastructure.ResponseType
import com.paychain.sdk.infrastructure.Success
import com.paychain.sdk.infrastructure.toMultiValue

open class StablecoinsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.paychain.cambobia.com")
        }
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/activate
     * Activate a stablecoin
     * 
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Stablecoin
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun activateStablecoin(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID? = null) : Stablecoin {
        val localVarResponse = activateStablecoinWithHttpInfo(stablecoinId = stablecoinId, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Stablecoin
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/activate
     * Activate a stablecoin
     * 
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Stablecoin?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun activateStablecoinWithHttpInfo(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID?) : ApiResponse<Stablecoin?> {
        val localVariableConfig = activateStablecoinRequestConfig(stablecoinId = stablecoinId, xCorrelationId = xCorrelationId)

        return request<Unit, Stablecoin>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation activateStablecoin
     *
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun activateStablecoinRequestConfig(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/stablecoins/{stablecoinId}/activate".replace("{"+"stablecoinId"+"}", encodeURIComponent(stablecoinId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/approve-gate
     * Approve a stablecoin gate
     * 
     * @param stablecoinId 
     * @param approveStablecoinGateRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Stablecoin
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun approveStablecoinGate(stablecoinId: kotlin.String, approveStablecoinGateRequest: ApproveStablecoinGateRequest, xCorrelationId: java.util.UUID? = null) : Stablecoin {
        val localVarResponse = approveStablecoinGateWithHttpInfo(stablecoinId = stablecoinId, approveStablecoinGateRequest = approveStablecoinGateRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Stablecoin
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/approve-gate
     * Approve a stablecoin gate
     * 
     * @param stablecoinId 
     * @param approveStablecoinGateRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Stablecoin?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun approveStablecoinGateWithHttpInfo(stablecoinId: kotlin.String, approveStablecoinGateRequest: ApproveStablecoinGateRequest, xCorrelationId: java.util.UUID?) : ApiResponse<Stablecoin?> {
        val localVariableConfig = approveStablecoinGateRequestConfig(stablecoinId = stablecoinId, approveStablecoinGateRequest = approveStablecoinGateRequest, xCorrelationId = xCorrelationId)

        return request<ApproveStablecoinGateRequest, Stablecoin>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation approveStablecoinGate
     *
     * @param stablecoinId 
     * @param approveStablecoinGateRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun approveStablecoinGateRequestConfig(stablecoinId: kotlin.String, approveStablecoinGateRequest: ApproveStablecoinGateRequest, xCorrelationId: java.util.UUID?) : RequestConfig<ApproveStablecoinGateRequest> {
        val localVariableBody = approveStablecoinGateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/stablecoins/{stablecoinId}/approve-gate".replace("{"+"stablecoinId"+"}", encodeURIComponent(stablecoinId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/stablecoins
     * Create a stablecoin control-plane record
     * Feature-flag gated; public issuance remains disabled until readiness gates pass.
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param createStablecoinRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Stablecoin
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createStablecoin(idempotencyKey: kotlin.String, createStablecoinRequest: CreateStablecoinRequest, xCorrelationId: java.util.UUID? = null) : Stablecoin {
        val localVarResponse = createStablecoinWithHttpInfo(idempotencyKey = idempotencyKey, createStablecoinRequest = createStablecoinRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Stablecoin
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/stablecoins
     * Create a stablecoin control-plane record
     * Feature-flag gated; public issuance remains disabled until readiness gates pass.
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param createStablecoinRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Stablecoin?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createStablecoinWithHttpInfo(idempotencyKey: kotlin.String, createStablecoinRequest: CreateStablecoinRequest, xCorrelationId: java.util.UUID?) : ApiResponse<Stablecoin?> {
        val localVariableConfig = createStablecoinRequestConfig(idempotencyKey = idempotencyKey, createStablecoinRequest = createStablecoinRequest, xCorrelationId = xCorrelationId)

        return request<CreateStablecoinRequest, Stablecoin>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createStablecoin
     *
     * @param idempotencyKey Required on replay-safe writes so retries cannot double-apply.
     * @param createStablecoinRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun createStablecoinRequestConfig(idempotencyKey: kotlin.String, createStablecoinRequest: CreateStablecoinRequest, xCorrelationId: java.util.UUID?) : RequestConfig<CreateStablecoinRequest> {
        val localVariableBody = createStablecoinRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        idempotencyKey.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/stablecoins",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/stablecoins/{stablecoinId}
     * Get a stablecoin
     * 
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Stablecoin
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getStablecoin(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID? = null) : Stablecoin {
        val localVarResponse = getStablecoinWithHttpInfo(stablecoinId = stablecoinId, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Stablecoin
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/stablecoins/{stablecoinId}
     * Get a stablecoin
     * 
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Stablecoin?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getStablecoinWithHttpInfo(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID?) : ApiResponse<Stablecoin?> {
        val localVariableConfig = getStablecoinRequestConfig(stablecoinId = stablecoinId, xCorrelationId = xCorrelationId)

        return request<Unit, Stablecoin>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getStablecoin
     *
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun getStablecoinRequestConfig(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/stablecoins/{stablecoinId}".replace("{"+"stablecoinId"+"}", encodeURIComponent(stablecoinId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/stablecoins
     * List stablecoins
     * Stablecoin features are disabled by default until readiness gates pass.
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return kotlin.collections.List<Stablecoin>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listStablecoins(xCorrelationId: java.util.UUID? = null) : kotlin.collections.List<Stablecoin> {
        val localVarResponse = listStablecoinsWithHttpInfo(xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Stablecoin>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/stablecoins
     * List stablecoins
     * Stablecoin features are disabled by default until readiness gates pass.
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<kotlin.collections.List<Stablecoin>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listStablecoinsWithHttpInfo(xCorrelationId: java.util.UUID?) : ApiResponse<kotlin.collections.List<Stablecoin>?> {
        val localVariableConfig = listStablecoinsRequestConfig(xCorrelationId = xCorrelationId)

        return request<Unit, kotlin.collections.List<Stablecoin>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listStablecoins
     *
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun listStablecoinsRequestConfig(xCorrelationId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/stablecoins",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/submit-for-review
     * Submit a stablecoin for review
     * 
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Stablecoin
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun submitStablecoinForReview(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID? = null) : Stablecoin {
        val localVarResponse = submitStablecoinForReviewWithHttpInfo(stablecoinId = stablecoinId, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Stablecoin
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/submit-for-review
     * Submit a stablecoin for review
     * 
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Stablecoin?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun submitStablecoinForReviewWithHttpInfo(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID?) : ApiResponse<Stablecoin?> {
        val localVariableConfig = submitStablecoinForReviewRequestConfig(stablecoinId = stablecoinId, xCorrelationId = xCorrelationId)

        return request<Unit, Stablecoin>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation submitStablecoinForReview
     *
     * @param stablecoinId 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun submitStablecoinForReviewRequestConfig(stablecoinId: kotlin.String, xCorrelationId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/stablecoins/{stablecoinId}/submit-for-review".replace("{"+"stablecoinId"+"}", encodeURIComponent(stablecoinId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/suspend
     * Suspend stablecoin minting, redemption, or both
     * 
     * @param stablecoinId 
     * @param suspendStablecoinRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return Stablecoin
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun suspendStablecoin(stablecoinId: kotlin.String, suspendStablecoinRequest: SuspendStablecoinRequest, xCorrelationId: java.util.UUID? = null) : Stablecoin {
        val localVarResponse = suspendStablecoinWithHttpInfo(stablecoinId = stablecoinId, suspendStablecoinRequest = suspendStablecoinRequest, xCorrelationId = xCorrelationId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Stablecoin
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/stablecoins/{stablecoinId}/suspend
     * Suspend stablecoin minting, redemption, or both
     * 
     * @param stablecoinId 
     * @param suspendStablecoinRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return ApiResponse<Stablecoin?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun suspendStablecoinWithHttpInfo(stablecoinId: kotlin.String, suspendStablecoinRequest: SuspendStablecoinRequest, xCorrelationId: java.util.UUID?) : ApiResponse<Stablecoin?> {
        val localVariableConfig = suspendStablecoinRequestConfig(stablecoinId = stablecoinId, suspendStablecoinRequest = suspendStablecoinRequest, xCorrelationId = xCorrelationId)

        return request<SuspendStablecoinRequest, Stablecoin>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation suspendStablecoin
     *
     * @param stablecoinId 
     * @param suspendStablecoinRequest 
     * @param xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @return RequestConfig
     */
    fun suspendStablecoinRequestConfig(stablecoinId: kotlin.String, suspendStablecoinRequest: SuspendStablecoinRequest, xCorrelationId: java.util.UUID?) : RequestConfig<SuspendStablecoinRequest> {
        val localVariableBody = suspendStablecoinRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xCorrelationId?.apply { localVariableHeaders["X-Correlation-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/stablecoins/{stablecoinId}/suspend".replace("{"+"stablecoinId"+"}", encodeURIComponent(stablecoinId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
