<?php
/**
 * StablecoinWorkflowsApi
 * PHP version 8.1
 *
 * @package  PayChainSdk
 * @author   PayChain
 * @link     https://developer.paychain.cambobia.com
 */

/**
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated for PayChain
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is generated for PayChain. Do not edit this file manually.
 * https://developer.paychain.cambobia.com
 * Do not edit the class manually.
 */

namespace PayChainSdk\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use PayChainSdk\ApiException;
use PayChainSdk\Configuration;
use PayChainSdk\HeaderSelector;
use PayChainSdk\FormDataProcessor;
use PayChainSdk\ObjectSerializer;

/**
 * StablecoinWorkflowsApi Class Doc Comment
 *
 * @package  PayChainSdk
 * @author   PayChain
 * @link     https://developer.paychain.cambobia.com
 */
class StablecoinWorkflowsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createMintRequest' => [
            'application/json',
        ],
        'createRedemptionRequest' => [
            'application/json',
        ],
        'quoteConversion' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation createMintRequest
     *
     * Create a mint request
     *
     * @param  string $id id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\MintRequest $mintRequest mintRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMintRequest'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array<string,mixed>
     */
    public function createMintRequest(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\MintRequest $mintRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createMintRequest'][0]
    ): array
    {
        list($response) = $this->createMintRequestWithHttpInfo($id, $idempotencyKey, $mintRequest, $xCorrelationId, $contentType);
        return $response;
    }

    /**
     * Operation createMintRequestWithHttpInfo
     *
     * Create a mint request
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\MintRequest $mintRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMintRequest'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMintRequestWithHttpInfo(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\MintRequest $mintRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createMintRequest'][0]
    ): array
    {
        $request = $this->createMintRequestRequest($id, $idempotencyKey, $mintRequest, $xCorrelationId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,mixed>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation createMintRequestAsync
     *
     * Create a mint request
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\MintRequest $mintRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMintRequest'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createMintRequestAsync(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\MintRequest $mintRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createMintRequest'][0]
    ): PromiseInterface
    {
        return $this->createMintRequestAsyncWithHttpInfo($id, $idempotencyKey, $mintRequest, $xCorrelationId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMintRequestAsyncWithHttpInfo
     *
     * Create a mint request
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\MintRequest $mintRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMintRequest'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createMintRequestAsyncWithHttpInfo(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\MintRequest $mintRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createMintRequest'][0]
    ): PromiseInterface
    {
        $returnType = 'array<string,mixed>';
        $request = $this->createMintRequestRequest($id, $idempotencyKey, $mintRequest, $xCorrelationId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMintRequest'
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\MintRequest $mintRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMintRequest'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createMintRequestRequest(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\MintRequest $mintRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createMintRequest'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling createMintRequest'
            );
        }

        // verify the required parameter 'idempotencyKey' is set
        if ($idempotencyKey === null || (is_array($idempotencyKey) && count($idempotencyKey) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $idempotencyKey when calling createMintRequest'
            );
        }
        if (strlen($idempotencyKey) > 200) {
            throw new InvalidArgumentException('invalid length for "$idempotencyKey" when calling StablecoinWorkflowsApi.createMintRequest, must be smaller than or equal to 200.');
        }
        if (strlen($idempotencyKey) < 1) {
            throw new InvalidArgumentException('invalid length for "$idempotencyKey" when calling StablecoinWorkflowsApi.createMintRequest, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'mintRequest' is set
        if ($mintRequest === null || (is_array($mintRequest) && count($mintRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $mintRequest when calling createMintRequest'
            );
        }



        $resourcePath = '/api/v1/stablecoins/{id}/mint-requests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($xCorrelationId !== null) {
            $headerParams['X-Correlation-Id'] = ObjectSerializer::toHeaderValue($xCorrelationId);
        }
        // header params
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotencyKey);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($mintRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($mintRequest));
            } else {
                $httpBody = $mintRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createRedemptionRequest
     *
     * Create a redemption request
     *
     * @param  string $id id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\RedemptionRequest $redemptionRequest redemptionRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRedemptionRequest'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array<string,mixed>
     */
    public function createRedemptionRequest(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\RedemptionRequest $redemptionRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createRedemptionRequest'][0]
    ): array
    {
        list($response) = $this->createRedemptionRequestWithHttpInfo($id, $idempotencyKey, $redemptionRequest, $xCorrelationId, $contentType);
        return $response;
    }

    /**
     * Operation createRedemptionRequestWithHttpInfo
     *
     * Create a redemption request
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\RedemptionRequest $redemptionRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRedemptionRequest'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function createRedemptionRequestWithHttpInfo(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\RedemptionRequest $redemptionRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createRedemptionRequest'][0]
    ): array
    {
        $request = $this->createRedemptionRequestRequest($id, $idempotencyKey, $redemptionRequest, $xCorrelationId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,mixed>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation createRedemptionRequestAsync
     *
     * Create a redemption request
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\RedemptionRequest $redemptionRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRedemptionRequest'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createRedemptionRequestAsync(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\RedemptionRequest $redemptionRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createRedemptionRequest'][0]
    ): PromiseInterface
    {
        return $this->createRedemptionRequestAsyncWithHttpInfo($id, $idempotencyKey, $redemptionRequest, $xCorrelationId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createRedemptionRequestAsyncWithHttpInfo
     *
     * Create a redemption request
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\RedemptionRequest $redemptionRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRedemptionRequest'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function createRedemptionRequestAsyncWithHttpInfo(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\RedemptionRequest $redemptionRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createRedemptionRequest'][0]
    ): PromiseInterface
    {
        $returnType = 'array<string,mixed>';
        $request = $this->createRedemptionRequestRequest($id, $idempotencyKey, $redemptionRequest, $xCorrelationId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createRedemptionRequest'
     *
     * @param  string $id (required)
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\RedemptionRequest $redemptionRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRedemptionRequest'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createRedemptionRequestRequest(
        string $id,
        string $idempotencyKey,
        \PayChainSdk\Model\RedemptionRequest $redemptionRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['createRedemptionRequest'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling createRedemptionRequest'
            );
        }

        // verify the required parameter 'idempotencyKey' is set
        if ($idempotencyKey === null || (is_array($idempotencyKey) && count($idempotencyKey) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $idempotencyKey when calling createRedemptionRequest'
            );
        }
        if (strlen($idempotencyKey) > 200) {
            throw new InvalidArgumentException('invalid length for "$idempotencyKey" when calling StablecoinWorkflowsApi.createRedemptionRequest, must be smaller than or equal to 200.');
        }
        if (strlen($idempotencyKey) < 1) {
            throw new InvalidArgumentException('invalid length for "$idempotencyKey" when calling StablecoinWorkflowsApi.createRedemptionRequest, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'redemptionRequest' is set
        if ($redemptionRequest === null || (is_array($redemptionRequest) && count($redemptionRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $redemptionRequest when calling createRedemptionRequest'
            );
        }



        $resourcePath = '/api/v1/stablecoins/{id}/redemptions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($xCorrelationId !== null) {
            $headerParams['X-Correlation-Id'] = ObjectSerializer::toHeaderValue($xCorrelationId);
        }
        // header params
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotencyKey);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($redemptionRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($redemptionRequest));
            } else {
                $httpBody = $redemptionRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation quoteConversion
     *
     * Quote a loyalty to stablecoin conversion
     *
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest conversionQuoteRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['quoteConversion'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array<string,mixed>
     */
    public function quoteConversion(
        string $idempotencyKey,
        \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['quoteConversion'][0]
    ): array
    {
        list($response) = $this->quoteConversionWithHttpInfo($idempotencyKey, $conversionQuoteRequest, $xCorrelationId, $contentType);
        return $response;
    }

    /**
     * Operation quoteConversionWithHttpInfo
     *
     * Quote a loyalty to stablecoin conversion
     *
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['quoteConversion'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of array<string,mixed>, HTTP status code, HTTP response headers (array of strings)
     */
    public function quoteConversionWithHttpInfo(
        string $idempotencyKey,
        \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['quoteConversion'][0]
    ): array
    {
        $request = $this->quoteConversionRequest($idempotencyKey, $conversionQuoteRequest, $xCorrelationId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,mixed>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation quoteConversionAsync
     *
     * Quote a loyalty to stablecoin conversion
     *
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['quoteConversion'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function quoteConversionAsync(
        string $idempotencyKey,
        \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['quoteConversion'][0]
    ): PromiseInterface
    {
        return $this->quoteConversionAsyncWithHttpInfo($idempotencyKey, $conversionQuoteRequest, $xCorrelationId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation quoteConversionAsyncWithHttpInfo
     *
     * Quote a loyalty to stablecoin conversion
     *
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['quoteConversion'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function quoteConversionAsyncWithHttpInfo(
        string $idempotencyKey,
        \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['quoteConversion'][0]
    ): PromiseInterface
    {
        $returnType = 'array<string,mixed>';
        $request = $this->quoteConversionRequest($idempotencyKey, $conversionQuoteRequest, $xCorrelationId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'quoteConversion'
     *
     * @param  string $idempotencyKey Required on replay-safe writes so retries cannot double-apply. (required)
     * @param  \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest (required)
     * @param  string|null $xCorrelationId Optional caller-supplied correlation id echoed through logs and audit records. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['quoteConversion'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function quoteConversionRequest(
        string $idempotencyKey,
        \PayChainSdk\Model\ConversionQuoteRequest $conversionQuoteRequest,
        ?string $xCorrelationId = null,
        string $contentType = self::contentTypes['quoteConversion'][0]
    ): Request
    {

        // verify the required parameter 'idempotencyKey' is set
        if ($idempotencyKey === null || (is_array($idempotencyKey) && count($idempotencyKey) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $idempotencyKey when calling quoteConversion'
            );
        }
        if (strlen($idempotencyKey) > 200) {
            throw new InvalidArgumentException('invalid length for "$idempotencyKey" when calling StablecoinWorkflowsApi.quoteConversion, must be smaller than or equal to 200.');
        }
        if (strlen($idempotencyKey) < 1) {
            throw new InvalidArgumentException('invalid length for "$idempotencyKey" when calling StablecoinWorkflowsApi.quoteConversion, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'conversionQuoteRequest' is set
        if ($conversionQuoteRequest === null || (is_array($conversionQuoteRequest) && count($conversionQuoteRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $conversionQuoteRequest when calling quoteConversion'
            );
        }



        $resourcePath = '/api/v1/conversions/quote';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($xCorrelationId !== null) {
            $headerParams['X-Correlation-Id'] = ObjectSerializer::toHeaderValue($xCorrelationId);
        }
        // header params
        if ($idempotencyKey !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotencyKey);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($conversionQuoteRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($conversionQuoteRequest));
            } else {
                $httpBody = $conversionQuoteRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
