/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.paychain.sdk.models.Asset

class AssetTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Asset
        //val modelInstance = Asset()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `assetCode`
        should("test assetCode") {
            // uncomment below to test the property
            //modelInstance.assetCode shouldBe ("TODO")
        }

        // to test the property `assetName`
        should("test assetName") {
            // uncomment below to test the property
            //modelInstance.assetName shouldBe ("TODO")
        }

        // to test the property `assetType`
        should("test assetType") {
            // uncomment below to test the property
            //modelInstance.assetType shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `issuerPublicKey`
        should("test issuerPublicKey") {
            // uncomment below to test the property
            //modelInstance.issuerPublicKey shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
