/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.paychain.sdk.models.EarnRequest

class EarnRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EarnRequest
        //val modelInstance = EarnRequest()

        // to test the property `walletId`
        should("test walletId") {
            // uncomment below to test the property
            //modelInstance.walletId shouldBe ("TODO")
        }

        // to test the property `spendAmount`
        should("test spendAmount") {
            // uncomment below to test the property
            //modelInstance.spendAmount shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `merchantId`
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

    }
}
