/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.paychain.sdk.models.TokenRequest

class TokenRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TokenRequest
        //val modelInstance = TokenRequest()

        // to test the property `grantType`
        should("test grantType") {
            // uncomment below to test the property
            //modelInstance.grantType shouldBe ("TODO")
        }

        // to test the property `clientId`
        should("test clientId") {
            // uncomment below to test the property
            //modelInstance.clientId shouldBe ("TODO")
        }

        // to test the property `clientSecret`
        should("test clientSecret") {
            // uncomment below to test the property
            //modelInstance.clientSecret shouldBe ("TODO")
        }

    }
}
