'use client';

import { useCallback, useEffect, useState } from 'react';

interface AppRow {
  id: string;
  orgName: string;
  contactName: string;
  contactEmail: string;
  integrationType: string;
  status: string;
  reference: string;
  tenantId: string | null;
  rejectionReason: string | null;
  createdAt: string;
}

const STATUS_PILL: Record<string, string> = {
  PROVISIONED: 'PASSED',
  APPROVED: 'PASSED',
  REJECTED: 'BLOCKED',
  PENDING: 'IN_PROGRESS',
};

export default function PartnerApplicationsPage() {
  const [rows, setRows] = useState<AppRow[]>([]);
  const [perms, setPerms] = useState<string[]>([]);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');

  const canReview = perms.includes('partner:review');

  const load = useCallback(async () => {
    const r = await fetch('/api/partner-applications');
    if (r.ok) setRows(((await r.json()) as { items: AppRow[] }).items ?? []);
  }, []);

  useEffect(() => {
    void load();
    void fetch('/api/access-model')
      .then((r) => (r.ok ? r.json() : null))
      .then((m) => setPerms(m?.me?.permissions ?? []))
      .catch(() => undefined);
  }, [load]);

  async function act(id: string, path: 'approve' | 'reject') {
    setNotice('');
    setError('');
    const body =
      path === 'reject'
        ? JSON.stringify({ reason: prompt('Reason for rejection (emailed to the applicant):') ?? 'Not accepted at this time' })
        : undefined;
    const res = await fetch(`/api/partner-applications/${id}/${path}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      ...(body ? { body } : {}),
    });
    const data = await res.json().catch(() => ({}));
    if (res.ok) {
      setNotice(
        path === 'approve'
          ? `Approved — provisioned tenant + credentials (client ${data.clientId ?? ''}). The partner can now generate their secret.`
          : 'Rejected — the applicant has been notified.',
      );
      void load();
    } else setError(data.message ?? 'Action failed');
  }

  const pending = rows.filter((r) => r.status === 'PENDING');

  return (
    <>
      <div className="head-row">
        <h1>Partner Applications</h1>
        <span className="count">{rows.length} total · {pending.length} pending</span>
      </div>
      <p className="subtitle">
        Self-service partner registrations. Approving provisions a tenant + API credentials and emails
        the partner; the API secret is generated by the partner (shown once) in their onboarding dashboard.
      </p>

      {notice && <div className="ok-note" style={{ maxWidth: 820 }}>{notice}</div>}
      {error && <div className="login-error" style={{ maxWidth: 820 }}>{error}</div>}

      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>When</th>
              <th>Organisation</th>
              <th>Contact</th>
              <th>Type</th>
              <th>Status</th>
              <th>Tenant</th>
              {canReview && <th>Actions</th>}
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 && (
              <tr><td colSpan={canReview ? 7 : 6} style={{ color: 'var(--muted)' }}>No applications yet.</td></tr>
            )}
            {rows.map((r) => (
              <tr key={r.id}>
                <td style={{ fontSize: 12 }}>{new Date(r.createdAt).toLocaleString()}</td>
                <td>
                  {r.orgName}
                  <div className="mono" style={{ fontSize: 11, color: 'var(--muted)' }}>{r.reference}</div>
                </td>
                <td style={{ fontSize: 12 }}>
                  {r.contactName}
                  <div style={{ fontSize: 11, color: 'var(--muted)' }}>{r.contactEmail}</div>
                </td>
                <td><span className="mono" style={{ fontSize: 11 }}>{r.integrationType}</span></td>
                <td>
                  <span className={`pill ${STATUS_PILL[r.status] ?? 'IN_PROGRESS'}`}>{r.status}</span>
                  {r.rejectionReason && (
                    <div style={{ fontSize: 11, color: 'var(--muted)' }}>{r.rejectionReason}</div>
                  )}
                </td>
                <td className="mono" style={{ fontSize: 11 }}>{r.tenantId ?? '—'}</td>
                {canReview && (
                  <td>
                    {r.status === 'PENDING' && (
                      <div className="row-actions">
                        <button className="btn-sm" onClick={() => act(r.id, 'approve')}>Approve</button>
                        <button className="btn-sm" onClick={() => act(r.id, 'reject')}>Reject</button>
                      </div>
                    )}
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
