/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param assetCode 
 * @param assetName 
 * @param classification 
 * @param referenceCurrency 
 * @param issuerLegalEntity 
 * @param jurisdiction 
 * @param reserveRatioTarget 
 */


data class CreateStablecoinRequest (

    @Json(name = "assetCode")
    val assetCode: kotlin.String,

    @Json(name = "assetName")
    val assetName: kotlin.String,

    @Json(name = "classification")
    val classification: CreateStablecoinRequest.Classification,

    @Json(name = "referenceCurrency")
    val referenceCurrency: CreateStablecoinRequest.ReferenceCurrency,

    @Json(name = "issuerLegalEntity")
    val issuerLegalEntity: kotlin.String? = null,

    @Json(name = "jurisdiction")
    val jurisdiction: kotlin.String? = null,

    @Json(name = "reserveRatioTarget")
    val reserveRatioTarget: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: FIAT_BACKED_STABLECOIN,TOKENIZED_DEPOSIT,STABLE_VALUE_CREDIT
     */
    @JsonClass(generateAdapter = false)
    enum class Classification(val value: kotlin.String) {
        @Json(name = "FIAT_BACKED_STABLECOIN") FIAT_BACKED_STABLECOIN("FIAT_BACKED_STABLECOIN"),
        @Json(name = "TOKENIZED_DEPOSIT") TOKENIZED_DEPOSIT("TOKENIZED_DEPOSIT"),
        @Json(name = "STABLE_VALUE_CREDIT") STABLE_VALUE_CREDIT("STABLE_VALUE_CREDIT");
    }
    /**
     * 
     *
     * Values: USD,KHR
     */
    @JsonClass(generateAdapter = false)
    enum class ReferenceCurrency(val value: kotlin.String) {
        @Json(name = "USD") USD("USD"),
        @Json(name = "KHR") KHR("KHR");
    }

}

