/**
 *
 * Please note:
 * This class is generated for PayChain. Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ownerType 
 * @param ownerReference 
 * @param externalReference 
 */


data class CreateWalletRequest (

    @Json(name = "ownerType")
    val ownerType: CreateWalletRequest.OwnerType,

    @Json(name = "ownerReference")
    val ownerReference: kotlin.String,

    @Json(name = "externalReference")
    val externalReference: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: CUSTOMER,MERCHANT,ORGANIZATION,TREASURY,CAMPAIGN,SYSTEM,REDEMPTION,SETTLEMENT
     */
    @JsonClass(generateAdapter = false)
    enum class OwnerType(val value: kotlin.String) {
        @Json(name = "CUSTOMER") CUSTOMER("CUSTOMER"),
        @Json(name = "MERCHANT") MERCHANT("MERCHANT"),
        @Json(name = "ORGANIZATION") ORGANIZATION("ORGANIZATION"),
        @Json(name = "TREASURY") TREASURY("TREASURY"),
        @Json(name = "CAMPAIGN") CAMPAIGN("CAMPAIGN"),
        @Json(name = "SYSTEM") SYSTEM("SYSTEM"),
        @Json(name = "REDEMPTION") REDEMPTION("REDEMPTION"),
        @Json(name = "SETTLEMENT") SETTLEMENT("SETTLEMENT");
    }

}

