/**
 *
 * Please note:
 * This class is generated for PayChain. Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param destinationWalletId 
 * @param amount 
 * @param fundingReference 
 */


data class MintRequest (

    @Json(name = "destinationWalletId")
    val destinationWalletId: kotlin.String,

    @Json(name = "amount")
    val amount: kotlin.String,

    @Json(name = "fundingReference")
    val fundingReference: kotlin.String? = null

) {


}

