/**
 *
 * Please note:
 * This class is generated for PayChain. Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param mode 
 */


data class SuspendStablecoinRequest (

    @Json(name = "mode")
    val mode: SuspendStablecoinRequest.Mode

) {

    /**
     * 
     *
     * Values: MINTING_SUSPENDED,REDEMPTION_SUSPENDED,FULLY_SUSPENDED
     */
    @JsonClass(generateAdapter = false)
    enum class Mode(val value: kotlin.String) {
        @Json(name = "MINTING_SUSPENDED") MINTING_SUSPENDED("MINTING_SUSPENDED"),
        @Json(name = "REDEMPTION_SUSPENDED") REDEMPTION_SUSPENDED("REDEMPTION_SUSPENDED"),
        @Json(name = "FULLY_SUSPENDED") FULLY_SUSPENDED("FULLY_SUSPENDED");
    }

}

