/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.paychain.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param ownerType 
 * @param ownerReference 
 * @param stellarAccountId 
 * @param status 
 * @param createdAt 
 */


data class Wallet (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "ownerType")
    val ownerType: Wallet.OwnerType,

    @Json(name = "ownerReference")
    val ownerReference: kotlin.String,

    @Json(name = "stellarAccountId")
    val stellarAccountId: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime

) {

    /**
     * 
     *
     * Values: CUSTOMER,MERCHANT,ORGANIZATION,TREASURY,CAMPAIGN,SYSTEM,REDEMPTION,SETTLEMENT
     */
    @JsonClass(generateAdapter = false)
    enum class OwnerType(val value: kotlin.String) {
        @Json(name = "CUSTOMER") CUSTOMER("CUSTOMER"),
        @Json(name = "MERCHANT") MERCHANT("MERCHANT"),
        @Json(name = "ORGANIZATION") ORGANIZATION("ORGANIZATION"),
        @Json(name = "TREASURY") TREASURY("TREASURY"),
        @Json(name = "CAMPAIGN") CAMPAIGN("CAMPAIGN"),
        @Json(name = "SYSTEM") SYSTEM("SYSTEM"),
        @Json(name = "REDEMPTION") REDEMPTION("REDEMPTION"),
        @Json(name = "SETTLEMENT") SETTLEMENT("SETTLEMENT");
    }

}

