// <auto-generated>
/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using PayChain.Sdk.Client;

namespace PayChain.Sdk.Model
{
    /// <summary>
    /// IssueRequest
    /// </summary>
    public partial class IssueRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueRequest" /> class.
        /// </summary>
        /// <param name="destinationWalletId">destinationWalletId</param>
        /// <param name="amount">amount</param>
        [JsonConstructor]
        public IssueRequest(string destinationWalletId, string amount)
        {
            DestinationWalletId = destinationWalletId;
            Amount = amount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets DestinationWalletId
        /// </summary>
        [JsonPropertyName("destinationWalletId")]
        public string DestinationWalletId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        /* <example>100</example> */
        [JsonPropertyName("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IssueRequest {\n");
            sb.Append("  DestinationWalletId: ").Append(DestinationWalletId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssueRequest" />
    /// </summary>
    public class IssueRequestJsonConverter : JsonConverter<IssueRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="IssueRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IssueRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> destinationWalletId = default;
            Option<string?> amount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "destinationWalletId":
                            destinationWalletId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!destinationWalletId.IsSet)
                throw new ArgumentException("Property is required for class IssueRequest.", nameof(destinationWalletId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class IssueRequest.", nameof(amount));

            if (destinationWalletId.IsSet && destinationWalletId.Value == null)
                throw new ArgumentNullException(nameof(destinationWalletId), "Property is not nullable for class IssueRequest.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class IssueRequest.");

            return new IssueRequest(destinationWalletId.Value!, amount.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="IssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IssueRequest issueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, issueRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IssueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IssueRequest issueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (issueRequest.DestinationWalletId == null)
                throw new ArgumentNullException(nameof(issueRequest.DestinationWalletId), "Property is required for class IssueRequest.");

            if (issueRequest.Amount == null)
                throw new ArgumentNullException(nameof(issueRequest.Amount), "Property is required for class IssueRequest.");

            writer.WriteString("destinationWalletId", issueRequest.DestinationWalletId);

            writer.WriteString("amount", issueRequest.Amount);
        }
    }
}
