// <auto-generated>
/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated for PayChain internal and approved partner distribution.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using PayChain.Sdk.Client;

namespace PayChain.Sdk.Model
{
    /// <summary>
    /// RedemptionRequest
    /// </summary>
    public partial class RedemptionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RedemptionRequest" /> class.
        /// </summary>
        /// <param name="walletId">walletId</param>
        /// <param name="amount">amount</param>
        /// <param name="bankAccountReference">bankAccountReference</param>
        [JsonConstructor]
        public RedemptionRequest(string walletId, string amount, string bankAccountReference)
        {
            WalletId = walletId;
            Amount = amount;
            BankAccountReference = bankAccountReference;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets WalletId
        /// </summary>
        [JsonPropertyName("walletId")]
        public string WalletId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        /* <example>1000</example> */
        [JsonPropertyName("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Gets or Sets BankAccountReference
        /// </summary>
        [JsonPropertyName("bankAccountReference")]
        public string BankAccountReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RedemptionRequest {\n");
            sb.Append("  WalletId: ").Append(WalletId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  BankAccountReference: ").Append(BankAccountReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RedemptionRequest" />
    /// </summary>
    public class RedemptionRequestJsonConverter : JsonConverter<RedemptionRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="RedemptionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RedemptionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> walletId = default;
            Option<string?> amount = default;
            Option<string?> bankAccountReference = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "walletId":
                            walletId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "bankAccountReference":
                            bankAccountReference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!walletId.IsSet)
                throw new ArgumentException("Property is required for class RedemptionRequest.", nameof(walletId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class RedemptionRequest.", nameof(amount));

            if (!bankAccountReference.IsSet)
                throw new ArgumentException("Property is required for class RedemptionRequest.", nameof(bankAccountReference));

            if (walletId.IsSet && walletId.Value == null)
                throw new ArgumentNullException(nameof(walletId), "Property is not nullable for class RedemptionRequest.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class RedemptionRequest.");

            if (bankAccountReference.IsSet && bankAccountReference.Value == null)
                throw new ArgumentNullException(nameof(bankAccountReference), "Property is not nullable for class RedemptionRequest.");

            return new RedemptionRequest(walletId.Value!, amount.Value!, bankAccountReference.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RedemptionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="redemptionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RedemptionRequest redemptionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, redemptionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RedemptionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="redemptionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RedemptionRequest redemptionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (redemptionRequest.WalletId == null)
                throw new ArgumentNullException(nameof(redemptionRequest.WalletId), "Property is required for class RedemptionRequest.");

            if (redemptionRequest.Amount == null)
                throw new ArgumentNullException(nameof(redemptionRequest.Amount), "Property is required for class RedemptionRequest.");

            if (redemptionRequest.BankAccountReference == null)
                throw new ArgumentNullException(nameof(redemptionRequest.BankAccountReference), "Property is required for class RedemptionRequest.");

            writer.WriteString("walletId", redemptionRequest.WalletId);

            writer.WriteString("amount", redemptionRequest.Amount);

            writer.WriteString("bankAccountReference", redemptionRequest.BankAccountReference);
        }
    }
}
