// <auto-generated>
/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using PayChain.Sdk.Client;

namespace PayChain.Sdk.Model
{
    /// <summary>
    /// Transaction
    /// </summary>
    public partial class Transaction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="type">type</param>
        /// <param name="status">status</param>
        /// <param name="correlationId">correlationId</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="assetId">assetId</param>
        /// <param name="sourceWalletId">sourceWalletId</param>
        /// <param name="destinationWalletId">destinationWalletId</param>
        /// <param name="amount">amount</param>
        /// <param name="blockchainHash">blockchainHash</param>
        /// <param name="compensatesTransactionId">compensatesTransactionId</param>
        /// <param name="businessReason">businessReason</param>
        [JsonConstructor]
        public Transaction(string id, string tenantId, string type, string status, Guid correlationId, DateTimeOffset createdAt, Option<string?> assetId = default, Option<string?> sourceWalletId = default, Option<string?> destinationWalletId = default, Option<string?> amount = default, Option<string?> blockchainHash = default, Option<string?> compensatesTransactionId = default, Option<string?> businessReason = default)
        {
            Id = id;
            TenantId = tenantId;
            Type = type;
            Status = status;
            CorrelationId = correlationId;
            CreatedAt = createdAt;
            AssetIdOption = assetId;
            SourceWalletIdOption = sourceWalletId;
            DestinationWalletIdOption = destinationWalletId;
            AmountOption = amount;
            BlockchainHashOption = blockchainHash;
            CompensatesTransactionIdOption = compensatesTransactionId;
            BusinessReasonOption = businessReason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CorrelationId
        /// </summary>
        [JsonPropertyName("correlationId")]
        public Guid CorrelationId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of AssetId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssetIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("assetId")]
        public string? AssetId { get { return this.AssetIdOption.Value; } set { this.AssetIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceWalletId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceWalletIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceWalletId
        /// </summary>
        [JsonPropertyName("sourceWalletId")]
        public string? SourceWalletId { get { return this.SourceWalletIdOption.Value; } set { this.SourceWalletIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of DestinationWalletId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DestinationWalletIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DestinationWalletId
        /// </summary>
        [JsonPropertyName("destinationWalletId")]
        public string? DestinationWalletId { get { return this.DestinationWalletIdOption.Value; } set { this.DestinationWalletIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public string? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of BlockchainHash
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BlockchainHashOption { get; private set; }

        /// <summary>
        /// Gets or Sets BlockchainHash
        /// </summary>
        [JsonPropertyName("blockchainHash")]
        public string? BlockchainHash { get { return this.BlockchainHashOption.Value; } set { this.BlockchainHashOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompensatesTransactionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompensatesTransactionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompensatesTransactionId
        /// </summary>
        [JsonPropertyName("compensatesTransactionId")]
        public string? CompensatesTransactionId { get { return this.CompensatesTransactionIdOption.Value; } set { this.CompensatesTransactionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of BusinessReason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BusinessReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets BusinessReason
        /// </summary>
        [JsonPropertyName("businessReason")]
        public string? BusinessReason { get { return this.BusinessReasonOption.Value; } set { this.BusinessReasonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Transaction {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  SourceWalletId: ").Append(SourceWalletId).Append("\n");
            sb.Append("  DestinationWalletId: ").Append(DestinationWalletId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  BlockchainHash: ").Append(BlockchainHash).Append("\n");
            sb.Append("  CompensatesTransactionId: ").Append(CompensatesTransactionId).Append("\n");
            sb.Append("  BusinessReason: ").Append(BusinessReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Transaction" />
    /// </summary>
    public class TransactionJsonConverter : JsonConverter<Transaction>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Transaction" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Transaction Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> tenantId = default;
            Option<string?> type = default;
            Option<string?> status = default;
            Option<Guid?> correlationId = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<string?> assetId = default;
            Option<string?> sourceWalletId = default;
            Option<string?> destinationWalletId = default;
            Option<string?> amount = default;
            Option<string?> blockchainHash = default;
            Option<string?> compensatesTransactionId = default;
            Option<string?> businessReason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "correlationId":
                            correlationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "assetId":
                            assetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceWalletId":
                            sourceWalletId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "destinationWalletId":
                            destinationWalletId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "blockchainHash":
                            blockchainHash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "compensatesTransactionId":
                            compensatesTransactionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "businessReason":
                            businessReason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(id));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(tenantId));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(type));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(status));

            if (!correlationId.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(correlationId));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Transaction.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class Transaction.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Transaction.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Transaction.");

            if (correlationId.IsSet && correlationId.Value == null)
                throw new ArgumentNullException(nameof(correlationId), "Property is not nullable for class Transaction.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Transaction.");

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class Transaction.");

            if (sourceWalletId.IsSet && sourceWalletId.Value == null)
                throw new ArgumentNullException(nameof(sourceWalletId), "Property is not nullable for class Transaction.");

            if (destinationWalletId.IsSet && destinationWalletId.Value == null)
                throw new ArgumentNullException(nameof(destinationWalletId), "Property is not nullable for class Transaction.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class Transaction.");

            if (blockchainHash.IsSet && blockchainHash.Value == null)
                throw new ArgumentNullException(nameof(blockchainHash), "Property is not nullable for class Transaction.");

            if (compensatesTransactionId.IsSet && compensatesTransactionId.Value == null)
                throw new ArgumentNullException(nameof(compensatesTransactionId), "Property is not nullable for class Transaction.");

            if (businessReason.IsSet && businessReason.Value == null)
                throw new ArgumentNullException(nameof(businessReason), "Property is not nullable for class Transaction.");

            return new Transaction(id.Value!, tenantId.Value!, type.Value!, status.Value!, correlationId.Value!.Value!, createdAt.Value!.Value!, assetId, sourceWalletId, destinationWalletId, amount, blockchainHash, compensatesTransactionId, businessReason);
        }

        /// <summary>
        /// Serializes a <see cref="Transaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Transaction transaction, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, transaction, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Transaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Transaction transaction, JsonSerializerOptions jsonSerializerOptions)
        {
            if (transaction.Id == null)
                throw new ArgumentNullException(nameof(transaction.Id), "Property is required for class Transaction.");

            if (transaction.TenantId == null)
                throw new ArgumentNullException(nameof(transaction.TenantId), "Property is required for class Transaction.");

            if (transaction.Type == null)
                throw new ArgumentNullException(nameof(transaction.Type), "Property is required for class Transaction.");

            if (transaction.Status == null)
                throw new ArgumentNullException(nameof(transaction.Status), "Property is required for class Transaction.");

            if (transaction.AssetIdOption.IsSet && transaction.AssetId == null)
                throw new ArgumentNullException(nameof(transaction.AssetId), "Property is required for class Transaction.");

            if (transaction.SourceWalletIdOption.IsSet && transaction.SourceWalletId == null)
                throw new ArgumentNullException(nameof(transaction.SourceWalletId), "Property is required for class Transaction.");

            if (transaction.DestinationWalletIdOption.IsSet && transaction.DestinationWalletId == null)
                throw new ArgumentNullException(nameof(transaction.DestinationWalletId), "Property is required for class Transaction.");

            if (transaction.AmountOption.IsSet && transaction.Amount == null)
                throw new ArgumentNullException(nameof(transaction.Amount), "Property is required for class Transaction.");

            if (transaction.BlockchainHashOption.IsSet && transaction.BlockchainHash == null)
                throw new ArgumentNullException(nameof(transaction.BlockchainHash), "Property is required for class Transaction.");

            if (transaction.CompensatesTransactionIdOption.IsSet && transaction.CompensatesTransactionId == null)
                throw new ArgumentNullException(nameof(transaction.CompensatesTransactionId), "Property is required for class Transaction.");

            if (transaction.BusinessReasonOption.IsSet && transaction.BusinessReason == null)
                throw new ArgumentNullException(nameof(transaction.BusinessReason), "Property is required for class Transaction.");

            writer.WriteString("id", transaction.Id);

            writer.WriteString("tenantId", transaction.TenantId);

            writer.WriteString("type", transaction.Type);

            writer.WriteString("status", transaction.Status);

            writer.WriteString("correlationId", transaction.CorrelationId);

            writer.WriteString("createdAt", transaction.CreatedAt.ToString(CreatedAtFormat));

            if (transaction.AssetIdOption.IsSet)
                writer.WriteString("assetId", transaction.AssetId);

            if (transaction.SourceWalletIdOption.IsSet)
                writer.WriteString("sourceWalletId", transaction.SourceWalletId);

            if (transaction.DestinationWalletIdOption.IsSet)
                writer.WriteString("destinationWalletId", transaction.DestinationWalletId);

            if (transaction.AmountOption.IsSet)
                writer.WriteString("amount", transaction.Amount);

            if (transaction.BlockchainHashOption.IsSet)
                writer.WriteString("blockchainHash", transaction.BlockchainHash);

            if (transaction.CompensatesTransactionIdOption.IsSet)
                writer.WriteString("compensatesTransactionId", transaction.CompensatesTransactionId);

            if (transaction.BusinessReasonOption.IsSet)
                writer.WriteString("businessReason", transaction.BusinessReason);
        }
    }
}
