// <auto-generated>
/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using PayChain.Sdk.Client;

namespace PayChain.Sdk.Model
{
    /// <summary>
    /// Wallet
    /// </summary>
    public partial class Wallet : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Wallet" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="ownerType">ownerType</param>
        /// <param name="ownerReference">ownerReference</param>
        /// <param name="stellarAccountId">stellarAccountId</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        [JsonConstructor]
        public Wallet(string id, OwnerTypeEnum ownerType, string ownerReference, string stellarAccountId, string status, DateTimeOffset createdAt)
        {
            Id = id;
            OwnerType = ownerType;
            OwnerReference = ownerReference;
            StellarAccountId = stellarAccountId;
            Status = status;
            CreatedAt = createdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines OwnerType
        /// </summary>
        public enum OwnerTypeEnum
        {
            /// <summary>
            /// Enum CUSTOMER for value: CUSTOMER
            /// </summary>
            CUSTOMER = 1,

            /// <summary>
            /// Enum MERCHANT for value: MERCHANT
            /// </summary>
            MERCHANT = 2,

            /// <summary>
            /// Enum ORGANIZATION for value: ORGANIZATION
            /// </summary>
            ORGANIZATION = 3,

            /// <summary>
            /// Enum TREASURY for value: TREASURY
            /// </summary>
            TREASURY = 4,

            /// <summary>
            /// Enum CAMPAIGN for value: CAMPAIGN
            /// </summary>
            CAMPAIGN = 5,

            /// <summary>
            /// Enum SYSTEM for value: SYSTEM
            /// </summary>
            SYSTEM = 6,

            /// <summary>
            /// Enum REDEMPTION for value: REDEMPTION
            /// </summary>
            REDEMPTION = 7,

            /// <summary>
            /// Enum SETTLEMENT for value: SETTLEMENT
            /// </summary>
            SETTLEMENT = 8
        }

        /// <summary>
        /// Returns a <see cref="OwnerTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OwnerTypeEnum OwnerTypeEnumFromString(string value)
        {
            if (value.Equals("CUSTOMER"))
                return OwnerTypeEnum.CUSTOMER;

            if (value.Equals("MERCHANT"))
                return OwnerTypeEnum.MERCHANT;

            if (value.Equals("ORGANIZATION"))
                return OwnerTypeEnum.ORGANIZATION;

            if (value.Equals("TREASURY"))
                return OwnerTypeEnum.TREASURY;

            if (value.Equals("CAMPAIGN"))
                return OwnerTypeEnum.CAMPAIGN;

            if (value.Equals("SYSTEM"))
                return OwnerTypeEnum.SYSTEM;

            if (value.Equals("REDEMPTION"))
                return OwnerTypeEnum.REDEMPTION;

            if (value.Equals("SETTLEMENT"))
                return OwnerTypeEnum.SETTLEMENT;

            throw new NotImplementedException($"Could not convert value to type OwnerTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OwnerTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OwnerTypeEnum? OwnerTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("CUSTOMER"))
                return OwnerTypeEnum.CUSTOMER;

            if (value.Equals("MERCHANT"))
                return OwnerTypeEnum.MERCHANT;

            if (value.Equals("ORGANIZATION"))
                return OwnerTypeEnum.ORGANIZATION;

            if (value.Equals("TREASURY"))
                return OwnerTypeEnum.TREASURY;

            if (value.Equals("CAMPAIGN"))
                return OwnerTypeEnum.CAMPAIGN;

            if (value.Equals("SYSTEM"))
                return OwnerTypeEnum.SYSTEM;

            if (value.Equals("REDEMPTION"))
                return OwnerTypeEnum.REDEMPTION;

            if (value.Equals("SETTLEMENT"))
                return OwnerTypeEnum.SETTLEMENT;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OwnerTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OwnerTypeEnumToJsonValue(OwnerTypeEnum value)
        {
            if (value == OwnerTypeEnum.CUSTOMER)
                return "CUSTOMER";

            if (value == OwnerTypeEnum.MERCHANT)
                return "MERCHANT";

            if (value == OwnerTypeEnum.ORGANIZATION)
                return "ORGANIZATION";

            if (value == OwnerTypeEnum.TREASURY)
                return "TREASURY";

            if (value == OwnerTypeEnum.CAMPAIGN)
                return "CAMPAIGN";

            if (value == OwnerTypeEnum.SYSTEM)
                return "SYSTEM";

            if (value == OwnerTypeEnum.REDEMPTION)
                return "REDEMPTION";

            if (value == OwnerTypeEnum.SETTLEMENT)
                return "SETTLEMENT";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets OwnerType
        /// </summary>
        [JsonPropertyName("ownerType")]
        public OwnerTypeEnum OwnerType { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets OwnerReference
        /// </summary>
        [JsonPropertyName("ownerReference")]
        public string OwnerReference { get; set; }

        /// <summary>
        /// Gets or Sets StellarAccountId
        /// </summary>
        [JsonPropertyName("stellarAccountId")]
        public string StellarAccountId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /* <example>ACTIVE</example> */
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Wallet {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OwnerType: ").Append(OwnerType).Append("\n");
            sb.Append("  OwnerReference: ").Append(OwnerReference).Append("\n");
            sb.Append("  StellarAccountId: ").Append(StellarAccountId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Wallet" />
    /// </summary>
    public class WalletJsonConverter : JsonConverter<Wallet>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Wallet" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Wallet Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<Wallet.OwnerTypeEnum?> ownerType = default;
            Option<string?> ownerReference = default;
            Option<string?> stellarAccountId = default;
            Option<string?> status = default;
            Option<DateTimeOffset?> createdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ownerType":
                            string? ownerTypeRawValue = utf8JsonReader.GetString();
                            if (ownerTypeRawValue != null)
                                ownerType = new Option<Wallet.OwnerTypeEnum?>(Wallet.OwnerTypeEnumFromStringOrDefault(ownerTypeRawValue));
                            break;
                        case "ownerReference":
                            ownerReference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "stellarAccountId":
                            stellarAccountId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Wallet.", nameof(id));

            if (!ownerType.IsSet)
                throw new ArgumentException("Property is required for class Wallet.", nameof(ownerType));

            if (!ownerReference.IsSet)
                throw new ArgumentException("Property is required for class Wallet.", nameof(ownerReference));

            if (!stellarAccountId.IsSet)
                throw new ArgumentException("Property is required for class Wallet.", nameof(stellarAccountId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Wallet.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Wallet.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Wallet.");

            if (ownerType.IsSet && ownerType.Value == null)
                throw new ArgumentNullException(nameof(ownerType), "Property is not nullable for class Wallet.");

            if (ownerReference.IsSet && ownerReference.Value == null)
                throw new ArgumentNullException(nameof(ownerReference), "Property is not nullable for class Wallet.");

            if (stellarAccountId.IsSet && stellarAccountId.Value == null)
                throw new ArgumentNullException(nameof(stellarAccountId), "Property is not nullable for class Wallet.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Wallet.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Wallet.");

            return new Wallet(id.Value!, ownerType.Value!.Value!, ownerReference.Value!, stellarAccountId.Value!, status.Value!, createdAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Wallet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="wallet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Wallet wallet, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, wallet, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Wallet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="wallet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Wallet wallet, JsonSerializerOptions jsonSerializerOptions)
        {
            if (wallet.Id == null)
                throw new ArgumentNullException(nameof(wallet.Id), "Property is required for class Wallet.");

            if (wallet.OwnerReference == null)
                throw new ArgumentNullException(nameof(wallet.OwnerReference), "Property is required for class Wallet.");

            if (wallet.StellarAccountId == null)
                throw new ArgumentNullException(nameof(wallet.StellarAccountId), "Property is required for class Wallet.");

            if (wallet.Status == null)
                throw new ArgumentNullException(nameof(wallet.Status), "Property is required for class Wallet.");

            writer.WriteString("id", wallet.Id);

            var ownerTypeRawValue = Wallet.OwnerTypeEnumToJsonValue(wallet.OwnerType);
            writer.WriteString("ownerType", ownerTypeRawValue);
            writer.WriteString("ownerReference", wallet.OwnerReference);

            writer.WriteString("stellarAccountId", wallet.StellarAccountId);

            writer.WriteString("status", wallet.Status);

            writer.WriteString("createdAt", wallet.CreatedAt.ToString(CreatedAtFormat));
        }
    }
}
