// <auto-generated>
/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated for PayChain internal and approved partner distribution.
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using PayChain.Sdk.Client;

namespace PayChain.Sdk.Model
{
    /// <summary>
    /// WebhookEndpoint
    /// </summary>
    public partial class WebhookEndpoint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookEndpoint" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="url">url</param>
        /// <param name="events">events</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        [JsonConstructor]
        public WebhookEndpoint(string id, string url, List<string> events, string status, DateTimeOffset createdAt)
        {
            Id = id;
            Url = url;
            Events = events;
            Status = status;
            CreatedAt = createdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [JsonPropertyName("events")]
        public List<string> Events { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookEndpoint {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookEndpoint" />
    /// </summary>
    public class WebhookEndpointJsonConverter : JsonConverter<WebhookEndpoint>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="WebhookEndpoint" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebhookEndpoint Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> url = default;
            Option<List<string>?> events = default;
            Option<string?> status = default;
            Option<DateTimeOffset?> createdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "events":
                            events = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class WebhookEndpoint.", nameof(id));

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class WebhookEndpoint.", nameof(url));

            if (!events.IsSet)
                throw new ArgumentException("Property is required for class WebhookEndpoint.", nameof(events));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class WebhookEndpoint.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class WebhookEndpoint.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class WebhookEndpoint.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class WebhookEndpoint.");

            if (events.IsSet && events.Value == null)
                throw new ArgumentNullException(nameof(events), "Property is not nullable for class WebhookEndpoint.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class WebhookEndpoint.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class WebhookEndpoint.");

            return new WebhookEndpoint(id.Value!, url.Value!, events.Value!, status.Value!, createdAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="WebhookEndpoint" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookEndpoint"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WebhookEndpoint webhookEndpoint, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webhookEndpoint, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebhookEndpoint" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookEndpoint"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WebhookEndpoint webhookEndpoint, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webhookEndpoint.Id == null)
                throw new ArgumentNullException(nameof(webhookEndpoint.Id), "Property is required for class WebhookEndpoint.");

            if (webhookEndpoint.Url == null)
                throw new ArgumentNullException(nameof(webhookEndpoint.Url), "Property is required for class WebhookEndpoint.");

            if (webhookEndpoint.Events == null)
                throw new ArgumentNullException(nameof(webhookEndpoint.Events), "Property is required for class WebhookEndpoint.");

            if (webhookEndpoint.Status == null)
                throw new ArgumentNullException(nameof(webhookEndpoint.Status), "Property is required for class WebhookEndpoint.");

            writer.WriteString("id", webhookEndpoint.Id);

            writer.WriteString("url", webhookEndpoint.Url);

            writer.WritePropertyName("events");
            JsonSerializer.Serialize(writer, webhookEndpoint.Events, jsonSerializerOptions);
            writer.WriteString("status", webhookEndpoint.Status);

            writer.WriteString("createdAt", webhookEndpoint.CreatedAt.ToString(CreatedAtFormat));
        }
    }
}
