// <auto-generated>
/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated for PayChain internal and approved partner distribution.
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using PayChain.Sdk.Client;
using PayChain.Sdk.Model;
using System.Diagnostics.CodeAnalysis;

namespace PayChain.Sdk.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IWalletsApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        WalletsApiEvents Events { get; }

        /// <summary>
        /// Create a managed custodial wallet
        /// </summary>
        /// <remarks>
        /// Creates the Stellar account and records the wallet under the caller tenant.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Required on replay-safe writes so retries cannot double-apply.</param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateWalletApiResponse"/>&gt;</returns>
        Task<ICreateWalletApiResponse> CreateWalletAsync(string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a managed custodial wallet
        /// </summary>
        /// <remarks>
        /// Creates the Stellar account and records the wallet under the caller tenant.
        /// </remarks>
        /// <param name="idempotencyKey">Required on replay-safe writes so retries cannot double-apply.</param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateWalletApiResponse"/>?&gt;</returns>
        Task<ICreateWalletApiResponse?> CreateWalletOrDefaultAsync(string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get a wallet
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetWalletApiResponse"/>&gt;</returns>
        Task<IGetWalletApiResponse> GetWalletAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get a wallet
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetWalletApiResponse"/>?&gt;</returns>
        Task<IGetWalletApiResponse?> GetWalletOrDefaultAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List wallet balances
        /// </summary>
        /// <remarks>
        /// Refreshes the rebuildable balance read model from chain before returning balances.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListWalletBalancesApiResponse"/>&gt;</returns>
        Task<IListWalletBalancesApiResponse> ListWalletBalancesAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List wallet balances
        /// </summary>
        /// <remarks>
        /// Refreshes the rebuildable balance read model from chain before returning balances.
        /// </remarks>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListWalletBalancesApiResponse"/>?&gt;</returns>
        Task<IListWalletBalancesApiResponse?> ListWalletBalancesOrDefaultAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ICreateWalletApiResponse"/>
    /// </summary>
    public interface ICreateWalletApiResponse : PayChain.Sdk.Client.IApiResponse, IOk<PayChain.Sdk.Model.Wallet?>, IBadRequest<PayChain.Sdk.Model.ErrorResponse?>, IUnauthorized<PayChain.Sdk.Model.ErrorResponse?>, IForbidden<PayChain.Sdk.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }
    }

    /// <summary>
    /// The <see cref="IGetWalletApiResponse"/>
    /// </summary>
    public interface IGetWalletApiResponse : PayChain.Sdk.Client.IApiResponse, IOk<PayChain.Sdk.Model.Wallet?>, INotFound<PayChain.Sdk.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// The <see cref="IListWalletBalancesApiResponse"/>
    /// </summary>
    public interface IListWalletBalancesApiResponse : PayChain.Sdk.Client.IApiResponse, IOk<List<Balance>?>, INotFound<PayChain.Sdk.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class WalletsApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCreateWallet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCreateWallet;

        internal void ExecuteOnCreateWallet(WalletsApi.CreateWalletApiResponse apiResponse)
        {
            OnCreateWallet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCreateWallet(Exception exception)
        {
            OnErrorCreateWallet?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetWallet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetWallet;

        internal void ExecuteOnGetWallet(WalletsApi.GetWalletApiResponse apiResponse)
        {
            OnGetWallet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetWallet(Exception exception)
        {
            OnErrorGetWallet?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnListWalletBalances;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorListWalletBalances;

        internal void ExecuteOnListWalletBalances(WalletsApi.ListWalletBalancesApiResponse apiResponse)
        {
            OnListWalletBalances?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorListWalletBalances(Exception exception)
        {
            OnErrorListWalletBalances?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class WalletsApi : IWalletsApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<WalletsApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public WalletsApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="OauthTokenProvider"/>
        /// </summary>
        public TokenProvider<OAuthToken> OauthTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WalletsApi(ILogger<WalletsApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, WalletsApiEvents walletsApiEvents,
            TokenProvider<OAuthToken> oauthTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<WalletsApi>();
            HttpClient = httpClient;
            Events = walletsApiEvents;
            OauthTokenProvider = oauthTokenProvider;
        }

        partial void FormatCreateWallet(ref string idempotencyKey, CreateWalletRequest createWalletRequest, ref Option<Guid> xCorrelationId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="idempotencyKey"></param>
        /// <param name="createWalletRequest"></param>
        /// <returns></returns>
        private void ValidateCreateWallet(string idempotencyKey, CreateWalletRequest createWalletRequest)
        {
            if (idempotencyKey == null)
                throw new ArgumentNullException(nameof(idempotencyKey));

            if (createWalletRequest == null)
                throw new ArgumentNullException(nameof(createWalletRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId"></param>
        private void AfterCreateWalletDefaultImplementation(ICreateWalletApiResponse apiResponseLocalVar, string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId)
        {
            bool suppressDefaultLog = false;
            AfterCreateWallet(ref suppressDefaultLog, apiResponseLocalVar, idempotencyKey, createWalletRequest, xCorrelationId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId"></param>
        partial void AfterCreateWallet(ref bool suppressDefaultLog, ICreateWalletApiResponse apiResponseLocalVar, string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId"></param>
        private void OnErrorCreateWalletDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCreateWallet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, idempotencyKey, createWalletRequest, xCorrelationId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId"></param>
        partial void OnErrorCreateWallet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId);

        /// <summary>
        /// Create a managed custodial wallet Creates the Stellar account and records the wallet under the caller tenant.
        /// </summary>
        /// <param name="idempotencyKey">Required on replay-safe writes so retries cannot double-apply.</param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateWalletApiResponse"/>&gt;</returns>
        public async Task<ICreateWalletApiResponse?> CreateWalletOrDefaultAsync(string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CreateWalletAsync(idempotencyKey, createWalletRequest, xCorrelationId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Create a managed custodial wallet Creates the Stellar account and records the wallet under the caller tenant.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Required on replay-safe writes so retries cannot double-apply.</param>
        /// <param name="createWalletRequest"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateWalletApiResponse"/>&gt;</returns>
        public async Task<ICreateWalletApiResponse> CreateWalletAsync(string idempotencyKey, CreateWalletRequest createWalletRequest, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCreateWallet(idempotencyKey, createWalletRequest);

                FormatCreateWallet(ref idempotencyKey, createWalletRequest, ref xCorrelationId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/wallets"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v1/wallets");

                    httpRequestMessageLocalVar.Content = (createWalletRequest as object) is PayChain.Sdk.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(createWalletRequest, _jsonSerializerOptions));

                    // Set client side default value of Header Param "Idempotency-Key".                    
                    if (ClientUtils.IsContentHeader("Idempotency-Key"))
                    {
                        httpRequestMessageLocalVar.Content?.Headers.Add("Idempotency-Key", ClientUtils.ParameterToString(idempotencyKey));
                    }
                    else
                    {
                        httpRequestMessageLocalVar.Headers.Add("Idempotency-Key", ClientUtils.ParameterToString(idempotencyKey));
                    }

                    if (xCorrelationId.IsSet)
                    {
                      // Set client side default value of Header Param "X-Correlation-Id".                    
                      if (ClientUtils.IsContentHeader("X-Correlation-Id"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("X-Correlation-Id", ClientUtils.ParameterToString(xCorrelationId.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("X-Correlation-Id", ClientUtils.ParameterToString(xCorrelationId.Value));
                      }
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    OAuthToken oauthTokenLocalVar1 = (OAuthToken) await OauthTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(oauthTokenLocalVar1);

                    oauthTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<CreateWalletApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<CreateWalletApiResponse>();
                        CreateWalletApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/wallets", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCreateWalletDefaultImplementation(apiResponseLocalVar, idempotencyKey, createWalletRequest, xCorrelationId);

                        Events.ExecuteOnCreateWallet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCreateWalletDefaultImplementation(e, "/api/v1/wallets", uriBuilderLocalVar.Path, idempotencyKey, createWalletRequest, xCorrelationId);
                Events.ExecuteOnErrorCreateWallet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CreateWalletApiResponse"/>
        /// </summary>
        public partial class CreateWalletApiResponse : PayChain.Sdk.Client.ApiResponse, ICreateWalletApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<CreateWalletApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="CreateWalletApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateWalletApiResponse(ILogger<CreateWalletApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CreateWalletApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateWalletApiResponse(ILogger<CreateWalletApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public PayChain.Sdk.Model.Wallet? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<PayChain.Sdk.Model.Wallet>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out PayChain.Sdk.Model.Wallet? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public PayChain.Sdk.Model.ErrorResponse? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<PayChain.Sdk.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out PayChain.Sdk.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public PayChain.Sdk.Model.ErrorResponse? Unauthorized()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<PayChain.Sdk.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out PayChain.Sdk.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public PayChain.Sdk.Model.ErrorResponse? Forbidden()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<PayChain.Sdk.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out PayChain.Sdk.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetWallet(ref string walletId, ref Option<Guid> xCorrelationId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="walletId"></param>
        /// <returns></returns>
        private void ValidateGetWallet(string walletId)
        {
            if (walletId == null)
                throw new ArgumentNullException(nameof(walletId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        private void AfterGetWalletDefaultImplementation(IGetWalletApiResponse apiResponseLocalVar, string walletId, Option<Guid> xCorrelationId)
        {
            bool suppressDefaultLog = false;
            AfterGetWallet(ref suppressDefaultLog, apiResponseLocalVar, walletId, xCorrelationId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        partial void AfterGetWallet(ref bool suppressDefaultLog, IGetWalletApiResponse apiResponseLocalVar, string walletId, Option<Guid> xCorrelationId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        private void OnErrorGetWalletDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string walletId, Option<Guid> xCorrelationId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetWallet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, walletId, xCorrelationId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        partial void OnErrorGetWallet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string walletId, Option<Guid> xCorrelationId);

        /// <summary>
        /// Get a wallet 
        /// </summary>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetWalletApiResponse"/>&gt;</returns>
        public async Task<IGetWalletApiResponse?> GetWalletOrDefaultAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetWalletAsync(walletId, xCorrelationId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get a wallet 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetWalletApiResponse"/>&gt;</returns>
        public async Task<IGetWalletApiResponse> GetWalletAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetWallet(walletId);

                FormatGetWallet(ref walletId, ref xCorrelationId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/wallets/{walletId}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v1/wallets/{walletId}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BwalletId%7D", Uri.EscapeDataString(walletId.ToString()));

                    if (xCorrelationId.IsSet)
                    {
                      // Set client side default value of Header Param "X-Correlation-Id".                    
                      if (ClientUtils.IsContentHeader("X-Correlation-Id"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("X-Correlation-Id", ClientUtils.ParameterToString(xCorrelationId.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("X-Correlation-Id", ClientUtils.ParameterToString(xCorrelationId.Value));
                      }
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    OAuthToken oauthTokenLocalVar1 = (OAuthToken) await OauthTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(oauthTokenLocalVar1);

                    oauthTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<GetWalletApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetWalletApiResponse>();
                        GetWalletApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/wallets/{walletId}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetWalletDefaultImplementation(apiResponseLocalVar, walletId, xCorrelationId);

                        Events.ExecuteOnGetWallet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetWalletDefaultImplementation(e, "/api/v1/wallets/{walletId}", uriBuilderLocalVar.Path, walletId, xCorrelationId);
                Events.ExecuteOnErrorGetWallet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetWalletApiResponse"/>
        /// </summary>
        public partial class GetWalletApiResponse : PayChain.Sdk.Client.ApiResponse, IGetWalletApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetWalletApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetWalletApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetWalletApiResponse(ILogger<GetWalletApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetWalletApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetWalletApiResponse(ILogger<GetWalletApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public PayChain.Sdk.Model.Wallet? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<PayChain.Sdk.Model.Wallet>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out PayChain.Sdk.Model.Wallet? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public PayChain.Sdk.Model.ErrorResponse? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<PayChain.Sdk.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out PayChain.Sdk.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatListWalletBalances(ref string walletId, ref Option<Guid> xCorrelationId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="walletId"></param>
        /// <returns></returns>
        private void ValidateListWalletBalances(string walletId)
        {
            if (walletId == null)
                throw new ArgumentNullException(nameof(walletId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        private void AfterListWalletBalancesDefaultImplementation(IListWalletBalancesApiResponse apiResponseLocalVar, string walletId, Option<Guid> xCorrelationId)
        {
            bool suppressDefaultLog = false;
            AfterListWalletBalances(ref suppressDefaultLog, apiResponseLocalVar, walletId, xCorrelationId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        partial void AfterListWalletBalances(ref bool suppressDefaultLog, IListWalletBalancesApiResponse apiResponseLocalVar, string walletId, Option<Guid> xCorrelationId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        private void OnErrorListWalletBalancesDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string walletId, Option<Guid> xCorrelationId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorListWalletBalances(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, walletId, xCorrelationId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId"></param>
        partial void OnErrorListWalletBalances(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string walletId, Option<Guid> xCorrelationId);

        /// <summary>
        /// List wallet balances Refreshes the rebuildable balance read model from chain before returning balances.
        /// </summary>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListWalletBalancesApiResponse"/>&gt;</returns>
        public async Task<IListWalletBalancesApiResponse?> ListWalletBalancesOrDefaultAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ListWalletBalancesAsync(walletId, xCorrelationId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// List wallet balances Refreshes the rebuildable balance read model from chain before returning balances.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="walletId"></param>
        /// <param name="xCorrelationId">Optional caller-supplied correlation id echoed through logs and audit records. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListWalletBalancesApiResponse"/>&gt;</returns>
        public async Task<IListWalletBalancesApiResponse> ListWalletBalancesAsync(string walletId, Option<Guid> xCorrelationId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateListWalletBalances(walletId);

                FormatListWalletBalances(ref walletId, ref xCorrelationId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/wallets/{walletId}/balances"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v1/wallets/{walletId}/balances");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BwalletId%7D", Uri.EscapeDataString(walletId.ToString()));

                    if (xCorrelationId.IsSet)
                    {
                      // Set client side default value of Header Param "X-Correlation-Id".                    
                      if (ClientUtils.IsContentHeader("X-Correlation-Id"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("X-Correlation-Id", ClientUtils.ParameterToString(xCorrelationId.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("X-Correlation-Id", ClientUtils.ParameterToString(xCorrelationId.Value));
                      }
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    OAuthToken oauthTokenLocalVar1 = (OAuthToken) await OauthTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(oauthTokenLocalVar1);

                    oauthTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<ListWalletBalancesApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ListWalletBalancesApiResponse>();
                        ListWalletBalancesApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/wallets/{walletId}/balances", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterListWalletBalancesDefaultImplementation(apiResponseLocalVar, walletId, xCorrelationId);

                        Events.ExecuteOnListWalletBalances(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorListWalletBalancesDefaultImplementation(e, "/api/v1/wallets/{walletId}/balances", uriBuilderLocalVar.Path, walletId, xCorrelationId);
                Events.ExecuteOnErrorListWalletBalances(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ListWalletBalancesApiResponse"/>
        /// </summary>
        public partial class ListWalletBalancesApiResponse : PayChain.Sdk.Client.ApiResponse, IListWalletBalancesApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ListWalletBalancesApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ListWalletBalancesApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListWalletBalancesApiResponse(ILogger<ListWalletBalancesApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ListWalletBalancesApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListWalletBalancesApiResponse(ILogger<ListWalletBalancesApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public List<Balance>? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<List<Balance>>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out List<Balance>? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public PayChain.Sdk.Model.ErrorResponse? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<PayChain.Sdk.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out PayChain.Sdk.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
