/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using PayChain.Sdk.Api;
using PayChain.Sdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace PayChain.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing AssetsApi
    /// </summary>
    public sealed class AssetsApiTests : ApiTestsBase
    {
        private readonly IAssetsApi _instance;

        public AssetsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAssetsApi>();
        }

        /// <summary>
        /// Test ActivateAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ActivateAssetAsyncTest()
        {
            string assetId = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.ActivateAssetAsync(assetId, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<Asset>(model);
        }

        /// <summary>
        /// Test BurnAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BurnAssetAsyncTest()
        {
            string assetId = default!;
            string idempotencyKey = default!;
            BurnRequest burnRequest = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.BurnAssetAsync(assetId, idempotencyKey, burnRequest, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<TransactionRecord>(model);
        }

        /// <summary>
        /// Test CreateAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateAssetAsyncTest()
        {
            string idempotencyKey = default!;
            CreateAssetRequest createAssetRequest = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.CreateAssetAsync(idempotencyKey, createAssetRequest, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<Asset>(model);
        }

        /// <summary>
        /// Test EarnAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EarnAssetAsyncTest()
        {
            string assetId = default!;
            string idempotencyKey = default!;
            EarnRequest earnRequest = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.EarnAssetAsync(assetId, idempotencyKey, earnRequest, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<TransactionRecord>(model);
        }

        /// <summary>
        /// Test GetAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetAssetAsyncTest()
        {
            string assetId = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.GetAssetAsync(assetId, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<Asset>(model);
        }

        /// <summary>
        /// Test IssueAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task IssueAssetAsyncTest()
        {
            string assetId = default!;
            string idempotencyKey = default!;
            IssueRequest issueRequest = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.IssueAssetAsync(assetId, idempotencyKey, issueRequest, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<TransactionRecord>(model);
        }

        /// <summary>
        /// Test ListAssets
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListAssetsAsyncTest()
        {
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.ListAssetsAsync(xCorrelationId);
            var model = response.Ok();
            Assert.IsType<List<Asset>>(model);
        }

        /// <summary>
        /// Test RedeemAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RedeemAssetAsyncTest()
        {
            string assetId = default!;
            string idempotencyKey = default!;
            RedeemRequest redeemRequest = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.RedeemAssetAsync(assetId, idempotencyKey, redeemRequest, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<TransactionRecord>(model);
        }

        /// <summary>
        /// Test TransferAsset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TransferAssetAsyncTest()
        {
            string assetId = default!;
            string idempotencyKey = default!;
            TransferRequest transferRequest = default!;
            Client.Option<Guid> xCorrelationId = default!;
            var response = await _instance.TransferAssetAsync(assetId, idempotencyKey, transferRequest, xCorrelationId);
            var model = response.Ok();
            Assert.IsType<TransactionRecord>(model);
        }
    }
}
