/*
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using PayChain.Sdk.Api;
using PayChain.Sdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace PayChain.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing AuthApi
    /// </summary>
    public sealed class AuthApiTests : ApiTestsBase
    {
        private readonly IAuthApi _instance;

        public AuthApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAuthApi>();
        }

        /// <summary>
        /// Test IssueAccessToken
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task IssueAccessTokenAsyncTest()
        {
            TokenRequest tokenRequest = default!;
            var response = await _instance.IssueAccessTokenAsync(tokenRequest);
            var model = response.Ok();
            Assert.IsType<TokenResponse>(model);
        }
    }
}
