<?php
/**
 * WebhookCreateRequestTest
 *
 * PHP version 8.1
 *
 * @package  PayChainSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayChain Public API
 *
 * Tenant-facing API for loyalty integrations today and stablecoin workflows once readiness gates pass. The TypeScript SDK is published separately; other platforms can integrate directly from this contract.
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PayChainSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebhookCreateRequestTest Class Doc Comment
 *
 * @description WebhookCreateRequest
 * @package     PayChainSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebhookCreateRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebhookCreateRequest"
     */
    public function testWebhookCreateRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
